NWACus/avy

.eslintrc.json
.github/workflows/ci.yaml
App.tsx
app.config.ts
components/AvalancheCenterForecastZonePolygons.tsx
components/AvalancheCenterLogo.tsx
components/AvalancheDangerIcon.tsx
components/AvalancheForecast.tsx
components/AvalancheForecastZonePolygon.tsx
components/AvalancheProblemCard.tsx
components/AvalancheProblemIcon.tsx
components/AvalancheProblemImage.tsx
components/AvalancheProblemLikelihoodLine.tsx
components/DangerRose.tsx
components/SeverityNumberLine.tsx
components/TelemetryStationData.tsx
components/TelemetryStationMap.tsx
hooks/useAvalancheForecast.ts
hooks/useAvalancheForecastFragment.ts
hooks/useMapLayer.ts
package.json
scripts/eslint.sh
types/snowbound.ts
yarn.lock

Most common warnings:
- unused imports
- using `let` instead of `const`
- using explicit types unnecessarily (i.e. `const num: number = 4`)

Setup ESLint and fix all the warnings and errors so far 

---

.github/workflows/publish.yaml

github: run both iOS and android builds

---

App.tsx

- Only init Sentry if it's configured correctly; otherwise warn
- Only add items to DevSettings if the package can be loaded (resolves https://sentry.io/organizations/nwac/issues/3823627003/?project=4504317393436672&query=is%3Aunresolved&referrer=issue-stream)

Make some of the app startup a bit safer

---

.github/workflows/ci.yaml
package.json
types/nationalAvalancheCenter/enums.test.ts
yarn.lock

- add jest support
- add a simple test module
- add tests to CI GitHub actions

Set up test infra

---

App.tsx
components/AvalancheForecastZoneMap.tsx
components/helpers/dangerText.ts
components/screens/ForecastScreen.tsx
components/screens/HomeScreen.tsx
components/screens/MapScreen.tsx

The "Danger Scale" isn't quite finished (still needs to be moved), but it's close.

Start styling the home screen

---

.github/workflows/preview.yaml

This gets PR comments working correctly for EAS update bundles

Fix auto-commenting when publishing updates through `eas update`

---

App.tsx
components/AvalancheForecastZoneMap.tsx
components/DangerScale.tsx
components/screens/MenuScreen.tsx
components/text/index.tsx
package.json
routes.ts
yarn.lock

- Created named components for each style of text the designers have outlined (this aligns with React Native guidance in https://reactnative.dev/docs/text)
- Added Lato font to project
- Created a debug screen to render all the text styles
- Re-styled the map view Danger Scale to align with latest mocks
map view | text rendering
--- | ---

Styling and fonts

---

.eslintrc.json
.prettierignore
components/AvalancheForecastZoneMap.tsx
components/AvalancheProblemImage.tsx
components/Card.tsx
components/DangerScale.tsx
components/HTMLRenderer.tsx
components/forecast/AvalancheForecast.tsx
components/forecast/AvalancheTab.tsx

- bugfix: disable touch on avalanche problem images: the component isn't fully baked yet
- bugfix: hide divider on collapsible cards, allow touch anywhere in header to toggle
- cleanup: get configuration for RenderHTML into a single component called `HTMLRenderer`, start using preferred fonts

Forecast page changes

---

components/AvalancheForecastZoneMap.tsx

quick fix!
before | after
--- | ---

Fix formatting of card when zone has no rating

---

components/AvalancheForecastZoneMap.tsx

I'll add some notes inline, but the easiest way to see what's going on is to look at the preview!

Animating zone card list in map view

---

components/AvalancheDangerTable.tsx
components/DangerScale.tsx
components/text/HTML.tsx

Need to get a preview build out of this PR before I feel totally confident, but this seems to be the very surprising source

Fix Android crash - invalid value passed to justifyContent

---

components/AvalancheDangerTable.tsx

This was supposed to go in as part of #69, I just forgot to save this change in the editor 🙈

tiny rename

---

components/core/View.test.tsx
package.json
yarn.lock

Add react-native-testing-library, add View tests

---

components/AvalancheForecastZonePolygon.tsx

Oops - this was supposed to go in as part of #78, but I got distracted and forgot to commit it 🙈

Add comment explaining a tricky bit of code

---

components/AvalancheForecastZoneMap.tsx
components/AvalancheForecastZonePolygon.tsx
components/TelemetryStationMap.tsx
components/helpers/geographicCoordinates.test.ts
components/helpers/geographicCoordinates.ts

Factor this to keep track of two points, instead of doing floating-point arithemtic, as that is lossy over many iterations and impossible to test. Fixed a small bug in the latitude delta during this refactor.

*: update the algorithm for bounding regions

---

components/AvalancheCenterLogo.tsx
components/forecast/AvalancheForecast.tsx
network/prefetchAllActiveForecasts.ts

avalanche forecast: show the correct logo in the back button

---

components/TabControl.tsx
components/forecast/AvalancheForecast.tsx
components/forecast/AvalancheTab.tsx
components/forecast/WeatherTab.tsx
components/forecast/useNWACWeatherForecast.test.tsx
components/forecast/useNWACWeatherForecast.ts
package.json
yarn.lock

there's still a few TODOs in here, but I think this is far enough along to check in - works in all zones and doesn't throw runtime errors.

First pass at the weather forecast

---

components/DangerScale.tsx

update to latest feedback in Figma, add in the "open url" functionality on the icon
https://user-images.githubusercontent.com/101196/214911140-d8630814-572b-424b-b58a-3727e447931b.mp4

tiny: Update styling of danger scale; add URL to open

---

components/AvalancheForecastZoneMap.tsx
components/AvalancheForecastZonePolygon.tsx
components/TelemetryStationMap.tsx

This needs to be integrated into the animation controller, and for *some* reason the offset callback broke swipe gestures on there, ...

map: ensure zones are not obstructed by other elements

---

components/forecast/WeatherTab.tsx
components/forecast/useNWACWeatherForecast.ts
hooks/useWeatherForecasts.test.tsx
hooks/useWeatherForecasts.ts

- add the synopsis section in a card (final design TBD)
- add correct publication and expiration dates
- move the hook to the `hooks` directory

Weather tweaks

---

App.tsx
components/DangerScale.tsx
components/content/InfoTooltip.tsx
components/forecast/AvalancheTab.tsx
components/forecast/WeatherTab.tsx
content/helpStrings.ts

- updated danger scale to newest designs
- added more info tooltips everywhere
- adjust tooltip alignment (fixes #92)
- force status bar text to be dark, since most (all?) of our screen backgrounds are light

Various design refinements

---

content/helpStrings.ts

helptext: add some paragraph breaks to a wall of text

---

components/AvalancheForecastZoneMap.tsx

map: remove ineffectual code

---

components/AvalancheForecastZoneMap.tsx

map: consider the card someone scrolled to as selected
---
map: ensure all cards are the same height
---
https://user-images.githubusercontent.com/7328370/216345306-e462430b-3998-4427-9229-e98d2cbfbb24.MP4

map: update card behavior

---

.github/actions/expo/channel/delete/action.yaml
.github/workflows/preview.yaml
.github/workflows/publish.yaml
.github/workflows/pull_request_closed.yaml

Going to close this one after opening to make sure it works correctly :)

New workflow: clean up expo channel when PR closed

---

components/forecast/AvalancheTab.tsx

forecast: update headers

---

components/forecast/WeatherTab.tsx

Couple of quick changes following up from design meeting!

Change weather data title, move synopsis to end

---

components/content/Button.tsx
components/form/TextField.tsx
components/observations/ObservationSchema.ts
components/observations/ObservationSubmit.tsx
components/observations/ObservationsPortal.tsx
components/screens/ObservationsScreen.tsx
package.json
yarn.lock

button corners more rounded, button text bolded | just the start of a form. some validations hooked up, doesn't submit anything yet
--- | ---

obs submission form work-in-progress, obs portal style tweaks

---

App.tsx
components/content/Dropdown.tsx
components/form/SelectField.tsx
components/form/TextField.tsx
components/observations/ObservationSubmit.tsx
package.json
theme/colors.ts
yarn.lock

Still some validation funkiness with this, I'm not sure that Formik is the form library to use with React Native. Will explore alternatives in a later PR
https://user-images.githubusercontent.com/101196/218515300-34990449-efc7-47c4-9cc2-9f604166321d.mp4

Zone selector in submit form

---

components/form/SelectField.tsx
components/form/TextField.tsx
components/observations/ObservationSchema.ts
components/observations/ObservationSubmit.tsx
components/observations/ObservationsPortal.tsx
package.json
yarn.lock

- Switch to `react-hook-form` package, get validation errors working
- Set autofill and keyboard type flags as appropriate
- Fix styling for header and footer
- Make view shrink when keyboard pops up

Submission form work: validation improvements, keyboard awareness, styling

---

components/content/InfoTooltip.tsx
components/weather_data/WeatherStationDetail.tsx

If a weather station has notes, display a bell and show the notes in a popup. Very similar to existing website behavior, but, you know, prettier too.

Display bell if notes exist, display notes in popup

---

components/content/Card.tsx
components/core/Divider.tsx
components/observations/ObservationSubmit.tsx
components/screens/MenuScreen.tsx
components/weather_data/WeatherStationDetail.tsx

- fix bug preventing scroll to bottom
- add 24 hour/7 day picker

Finishing the weather table

---

components/form/DateField.tsx
components/observations/ObservationSchema.ts
components/observations/ObservationSubmit.tsx
package.json
yarn.lock

Displays inline for iOS, and in a modal dialog for Android.

DatePicker for submit obs

---

components/form/Conditional.tsx
components/form/SelectField.tsx
components/form/SwitchField.tsx
components/observations/ObservationSchema.ts
components/observations/ObservationSubmit.tsx
components/observations/ObservationsPortal.tsx
package.json
yarn.lock

- Add SwitchField based on segmented control
- Add Conditional wrapper, for rendering additional form components based on other form values
- Add the "signs of instability" section to form
https://user-images.githubusercontent.com/101196/219823306-11d15ab2-b475-4285-8d6f-5b72769a7cb8.mov

More submit form work

---

components/form/LocationField.tsx

Fix for saved location not being used when location modal is re-opened

---

components/AvalancheForecastZonePolygon.tsx
hooks/useMapViewZones.ts

Finally got a chance to test this for real today and make sure it works as intended 😄 
https://user-images.githubusercontent.com/101196/220224246-9f8dd7e4-e2ba-46d2-90ba-26da8497ff74.mp4

Pulse map region color when an avalanche warning is in effect

---

components/form/Conditional.tsx
components/form/SelectField.tsx
components/form/TextField.tsx
components/observations/ObservationSchema.ts
components/observations/ObservationSubmit.tsx
components/text/index.tsx

fills in Snowpack, Observation Summary, Weather sections of the form. fixes some minor layout spacing issues.

More submit obs form fields

---

components/content/ZoneMap.tsx

Use a terrain map

---

app.json
components/content/Button.tsx
components/content/carousel/ImageList.tsx
components/form/LocationField.tsx
components/observations/ObservationSubmit.tsx
package.json
yarn.lock

Pick photos, unpick them, enforce 8 photo limit

Add photo picker to obs form

---

hooks/useLatestWeatherForecasts.ts

When scraping, allow for negative temperatures

---

components/core/VStack.tsx
components/core/View.tsx
components/form/SelectField.tsx
components/form/TextField.tsx
components/observations/AdvancedForm.tsx
components/observations/ObservationSchema.ts
components/observations/SimpleForm.tsx
components/screens/ObservationsScreen.tsx

- Set up a simple obs form to match what's seen in https://bridgertetonavalanchecenter.org/observations/#/form
- Add some new validation rules
- Implement scrolling to fields with errors on submit attempt
Next: actually submitting 😱 
https://user-images.githubusercontent.com/101196/221014477-2b2dacc3-2d78-4e08-a9fd-5c6ce663cd5f.mp4

Create the simplified observation form

---

components/AvalancheForecastZoneMap.tsx

Works in Simulator, we should check it on a couple of devices before merging

Place DangerScale wrapper accurately, push it down with margin

---

hooks/useCachedImageURI.ts

Fix for racy creation of image cache directory

---

App.tsx
hooks/useCachedImageURI.ts

hooks: improve cached image cleanup

---

components/forecast/AvalancheTab.tsx
components/forecast/WeatherTab.tsx
components/observations/ObservationDetailView.tsx
components/observations/ObservationsListView.tsx
components/screens/MenuScreen.tsx

observations/list: use the correct background color
---
components: use background.base for colors
---

observations/list: use the correct background color

---

App.tsx
package.json
yarn.lock

@yuliadub this might fix the Android timezone issue - I will need to build local APKs and test it out.

*: use a polyfill for timezones

---

.eslintrc.json
App.tsx
components/core/View.tsx
components/observations/ObservationDetailView.tsx
components/observations/ObservationsListView.tsx
components/observations/SimpleForm.tsx
components/observations/submitObservation.ts
components/screens/MenuScreen.tsx
components/screens/ObservationsScreen.tsx
hooks/logger.ts
hooks/useAvalancheCenterMetadata.ts
hooks/useAvalancheForecast.ts
hooks/useAvalancheForecastById.ts
hooks/useAvalancheForecastFragments.ts
hooks/useAvalancheWarning.ts
hooks/useMapLayer.ts
hooks/useNWACObservation.ts
hooks/useNWACObservations.ts
hooks/useNWACWeatherForecast.ts
hooks/useWeatherStations.ts
logger.ts
network/log.ts
package.json
scripts/getSnowboundOpenAPISpec.ts
yarn.lock

- update all existing log calls
- add ESLint rule to prevent direct console.log usage
- configuration probably still needs to be tweaked
in action:

Switch to `react-native-logs`

---

App.tsx
components/screens/MenuScreen.tsx
logger.ts
package.json
yarn.lock

Log to file. Add a button to send the logs.

Email logs

---

components/observations/ObservationDetailView.tsx
hooks/useNACObservation.ts

- create useNACObservation hook to get values from the REST API, use that in the obs detail view
- colored icons for instability

Single obs updates

---

components/screens/HomeScreen.tsx
routes.ts

Fixes issue reported by @charlotteguard

Fix navigation from forecast -> observation detail

---

components/content/carousel/ImageViewerModal.tsx
package.json
yarn.lock

This integrates a package for rendering the images in a modal and allowing zoom and pan. My only gripe with it is that it allows you to pan too far - you can pan the bottom of image almost to the top of the screen, for example. But other than that, it's a vast improvement over what we had before and makes the image browsing experience so much more useful.
https://user-images.githubusercontent.com/101196/222795836-68f93a58-f4d9-4d28-8957-18035a1751c3.mov

Image zoom and pan

---

components/observations/ObservationDetailView.tsx
components/screens/MenuScreen.tsx
logger.ts
update-contains.sh

menu: expose the update group version
We need to know both the update group and the specific update ID to
determine which JS bundle we're running.
---
logger: be idempotent in deletion of file
When the file doesn't exist, not deleting it is not an error.
---
*: add a script to debug relationship between commit and update
---

*: add a script to debug relationship between commit and update

---

components/content/carousel/index.tsx
components/forecast/WeatherTab.tsx
theme/colors.ts

- fix calculation for some of the colors - bug was introduced in #241 
- set border radius on image carousel
- fix text and border style for part of the weather tab

More design QA fixes

---

components/weather_data/WeatherStationDetail.tsx

Different weather stations may have different times at which they record data; we need to handle the case where our columns are not entirely 'full'.

weather_data: handle unaligned time series

---

components/AvalancheForecastZoneMap.tsx

Fixes https://github.com/stevekuznetsov/avalanche-forecast/issues/247

AvalancheForecastZoneMap: guard against missing reference

---

hooks/useAvalancheCenterMetadata.ts
hooks/useAvalancheForecast.ts
hooks/useAvalancheForecastById.ts
hooks/useAvalancheForecastFragments.ts
hooks/useAvalancheWarning.ts
hooks/useCachedImageURI.ts
hooks/useMapLayer.ts
hooks/useNACObservation.ts
hooks/useNWACObservation.ts
hooks/useNWACObservations.ts
hooks/useNWACWeatherForecast.ts
logger.ts
network/log.ts
network/prefetchAllActiveForecasts.ts

useCachedImageURI: fix URI access during cleanup
---
*: use structured logs
---
Fixes https://github.com/stevekuznetsov/avalanche-forecast/issues/246

useCachedImageURI: fix URI access during cleanup

---

components/AvalancheForecastZoneMap.tsx

Adds logging for https://github.com/stevekuznetsov/avalanche-forecast/issues/238

components/AvalancheForecastZoneMap: log region animations

---

App.tsx
components/AvalancheForecastZoneMap.tsx
components/content/Toast.tsx
components/content/carousel/NetworkImage.tsx
components/forecast/AvalancheTab.tsx
components/observations/ObservationsListView.tsx
components/observations/SimpleForm.tsx
components/screens/MenuScreen.tsx
package.json
routes.ts
yarn.lock

map: capture another input into the log
---
*: implement styled toasts, use them
---
forecast/AvalancheTab: show persistent toast when expired
---
observations: use a distinct color for forecasters
---
observations: don't go to image viewer modal in list
---

*: updates

---

components/forecast/AvalancheTab.tsx
components/screens/MenuScreen.tsx
hooks/useSynopsis.ts
network/prefetchAllActiveForecasts.ts
types/nationalAvalancheCenter/schemas.ts

*: add synopsis

---

components/AvalancheForecastZoneMap.tsx
components/content/InfoTooltip.tsx

InfoTooltip: fix background colors
Fixes https://github.com/stevekuznetsov/avalanche-forecast/issues/269
---
AvalancheForecastZoneCards: fix danger level text
Fixes https://github.com/stevekuznetsov/avalanche-forecast/issues/268
---
AvalancheForecastZoneMap: allow dynamic card heights
Fixes https://github.com/stevekuznetsov/avalanche-forecast/issues/264
---
AvalancheForecastZoneCards: reject non-human scrolls
Fixes https://github.com/stevekuznetsov/avalanche-forecast/issues/272
---

Misc Bug Fixes

---

components/forecast/AvalancheForecast.tsx
components/observations/ObservationsListView.tsx
hooks/useNACObservations.ts
hooks/useNWACObservations.ts
network/prefetchAllActiveForecasts.ts
types/nationalAvalancheCenter/schemas.ts

Centers opt into specific parts of the NAC platform and we can check for that, before we show parts of the app that will be non-functional for them.

*: use center config to determine what we load and show

---

components/forecast/AvalancheTab.tsx
components/screens/MenuScreen.tsx

| Special Bulletin|Avalanche Watch |
|-|-|
| ![IMG_0099](https://github.com/stevekuznetsov/avalanche-forecast/assets/7328370/a271c0f5-3a52-4de7-91c2-e85c02b1c3b7) | ![IMG_0100](https://github.com/stevekuznetsov/avalanche-forecast/assets/7328370/71fb9e8d-76bb-497c-a01a-7c6159101d6b) |

avalanche tab: disambiguate between watches, warnings and specials

---

components/forecast/AvalancheForecast.tsx
components/forecast/AvalancheTab.tsx
components/forecast/WeatherTab.tsx
components/screens/MenuScreen.tsx
hooks/useAvalancheForecast.ts
hooks/useNWACWeatherForecast.ts
hooks/useWeatherForecast.ts
network/prefetchAllActiveForecasts.ts
types/nationalAvalancheCenter/schemas.ts
validate-zod.ts

forecast: fix special bulletin color
---
forecast: add NAC weather forecasts
These display very much like the NWAC ones do. There's a historical data
format that we *could* support but it doesn't seem like it's been used
since 2020, so need to confirm there.
---

forecast: add NAC weather forecasts

---

Preferences.test.tsx
Preferences.tsx
package.json
yarn.lock

cc @stevekuznetsov, as suggested in #314

Zod preferences

---

App.tsx

Replace Home icon, rename to Map

---

components/screens/MenuScreen.tsx
package.json
yarn.lock

this was stupidly easy to do
https://github.com/stevekuznetsov/avalanche-forecast/assets/101196/6d4232e3-95ce-4bde-b401-71410c8f869e

Open links in an in-app browser

---

components/AvalancheForecastZoneMap.tsx

designer feedback request
before | after
--- | ---

remove 'Avalanche Danger' from zone cards

---

components/forecast/ObservationsTab.tsx
components/observations/ObservationsFilterForm.tsx
components/observations/ObservationsListView.tsx
theme/colors.ts

Worked with Erica on this design, it is still subject to change. Also, changing the filters seems *very* slow - will need to dig into that.
https://github.com/stevekuznetsov/avalanche-forecast/assets/101196/3a46c046-3bd4-444d-9999-f5b8358dcef0

Observation list filtering UI

---

.eslintrc.json
App.tsx
components/AvalancheCenterSelector.tsx
tamagui.config.ts

Import the correct ScrollView object

---

components/content/Outcome.tsx
components/content/QueryState.tsx
components/forecast/AvalancheTab.tsx
components/screens/MenuScreen.tsx

1. Put avalanche problem type in the forecast view
2. Make some adjustments to the outcome components
- center the images visually
- tighten spacing
- don't let header text wrap
1 | 2 | 3 | 4
--- | --- | --- | ---

Misc fixes

---

components/AvalancheForecastZoneMap.tsx

I am cautiously optimistic that this fixes #336 and all the other map weirdness we've observed. I think we were getting multiple animations running in parallel on the map camera, causing it to do weird things. Let's see if this does it.

Debounce map animation requests

---

components/observations/ObservationDetailView.tsx
components/screens/HomeScreen.tsx

Fix navigation from home screen -> observation

---

.env.sample
App.tsx
components/AvalancheForecastZoneMap.tsx
components/avalancheCenterList.ts
components/content/AvalancheCenterList.tsx
components/modals/AvalancheCenterSelectionModal.tsx
components/screens/MenuScreen.tsx

yes, it's the long-awaited "hide the debug menu" PR cc @yuliadub 
also the new design for the intro dialog
also should fix the annoyingly infrequent "No native splash screen registered" error

Hide debug menu in release builds; full screen center picker

---

components/content/Button.tsx

Buttons need to be Pressable all the way to the edge

---

.github/workflows/expo_preview.yaml

More fixes to expo-preview workflow

---

.github/actions/expo/channel/delete/action.yaml

Only try to delete the channel if it doesn't exist

Make pull request closed action more robust

---

.github/actions/expo/channel/delete/action.yaml

Make pull request closed action more robust (take 2)

---

components/AvalancheProblemSizeLine.tsx
components/SeverityNumberLine.tsx
components/screens/MenuScreen.tsx
routes.ts

Fixes #55 
https://github.com/NWACus/avy/assets/101196/19b03a6c-5d3f-42d9-ac0e-e4b40e5b8412

Fix avy size line rendering, add test screen

---

data/settingsMenuItems.ts

This is still pending review by @charlotteguard

Update NWAC text and links in About page

---

components/observations/ObservationsFilterForm.tsx
components/observations/ObservationsListView.tsx

observations/filter: react to zone changing

---

.github/workflows/pull_request_opened.yaml

Needed for https://github.com/NWACus/avy/issues/396

.github/workflows: enable CI for merge queue

---

components/weather_data/WeatherStationDetail.tsx

weather_data: compute an accumulated precip column

---

components/forecast/ObservationsTab.tsx
components/observations/ObservationsListView.tsx

Fix query state not being centered correctly

---

components/content/InfoTooltip.tsx
components/forecast/AvalancheTab.tsx
components/modals/AvalancheCenterSelectionModal.tsx

Fixing a few of the issues from https://docs.google.com/spreadsheets/d/1OeW-NtgpYO5EH0TS_dC0vA3PtG5kEQh8HHsvvCZEvQs/edit#gid=0
- dimmed backdrop behind InfoTooltip modals
- full width button on a couple of modals 
- avalanche warning style changes

Design fixes

---

components/form/DateField.tsx

took me _much_ longer to find the fix than it did to change the code. Fixes #334

Fix calendar picker not rendering in a modal

---

components/content/Dropdown.tsx

- Remove animation from modal presentation. Fixes problem with some clicks getting swallowed
- Move initial touch region so it's not shrunk by View padding
Definitely fixes #419 
Probably fixes #406

Dropdown fixes

---

types/nationalAvalancheCenter/schemas.ts

types/nationalAvalancheCenter: allow NWAC data entries to be null

---

components/content/InfoTooltip.tsx
components/core/View.test.tsx
components/text/index.tsx
theme/colors.ts

Fixes https://github.com/NWACus/avy/issues/416

colors.ts: ensure correct names are provided

---

components/form/DateField.tsx
components/form/LocationField.tsx
components/form/SwitchField.tsx
components/form/TextField.tsx
components/observations/SimpleForm.tsx

Disable form controls after submitting

---

App.tsx

Change Map => Zones

---

App.tsx
components/observations/ObservationsListView.tsx
components/screens/ObservationsScreen.tsx

https://github.com/NWACus/avy/assets/101196/ce4f55da-bdf2-436a-ba4a-716c34d972b6

Add a floating submit button to list view, change default screen to list view

---

.github/workflows/publish-update.yaml

Creating the PR to see if it works

Fix empty messages when calling eas update

---

components/observations/ObservationsListView.tsx
patches/@mobile-reality+react-native-select-pro+2.2.2.patch

Fixes #448, I just got sick of seeing the noise. Filed https://github.com/MobileReality/react-native-select-pro/issues/232 for an upstream fix on the console warnings.

Make submit button round. Patch react-native-select-pro.

---

components/AvalancheForecastZoneMap.tsx
components/content/Outcome.tsx
components/content/QueryState.tsx
components/forecast/WeatherTab.tsx
components/observations/ObservationsListView.tsx

Fix NotFound outcome styling for ObservationListView, AvalancheForecastZoneMap, WeatherTab

---

components/forecast/ObservationsTab.tsx
components/form/CheckboxSelectField.tsx
components/form/Conditional.tsx
components/form/DateField.tsx
components/form/SwitchField.tsx
components/observations/ObservationsFilterForm.tsx

I still have some questions about how the date picker is supposed to look/behave, but this brings things mostly into line with the Figma designs. Also fixes #260.
showing all zones | pinned to a single zone
--- | ---

Obs filter form

---

components/observations/ObservationsListView.tsx

Align submit button to right side of listview

---

components/observations/ObservationsListView.tsx

uploads in progress are displayed in a separate section with a greyed-out appearance. there might be a bit of iteration on the opacity level but this design seems basically locked.
code-wise, this uses a SectionList instead of FlatList, with a variable number of sections based on what we have going on.
appearance when we're not uploading is unchanged.
upload in progress | no upload
--- | ---

Updated styling for pending observation uploads

---

App.tsx
Preferences.test.tsx
components/helpers/geographicCoordinates.test.ts
hooks/useAvalancheForecastFragment.test.tsx
jest.config.ts
logger.ts
logging/fileStream.ts
tests/mockSentry.ts
types/nationalAvalancheCenter/schemas.ts

1. try to fix errors around SplashScreen.hideAsync
2. try to root out issues when flushing the log
3. fix validation errors from MSAC #469 - this will unbreak the center selection screen

Sentry errors

---

components/forecast/WeatherTab.tsx
components/map/AnimatedCards.tsx
components/observations/ObservationsListView.tsx
components/screens/WeatherScreen.tsx
components/weather_data/NWACWeatherStationList.tsx
components/weather_data/WeatherStationDetail.tsx
components/weather_data/WeatherStationFilterForm.tsx
components/weather_data/WeatherStationList.tsx
components/weather_data/WeatherStationMap.tsx
components/weather_data/WeatherStationPage.tsx
eas.json
network/prefetchAllActiveForecasts.ts
types/nationalAvalancheCenter/schemas.ts

This is a copy of #441 
---
Still a work-in-progress, outstanding items:
- getting the "list view" button to hover on top of the cards is not working perfectly - I have not found how to bind the pan response events to the animated value for the button, since we need it to be an offset from the value for the cards; I tried event listeners but they don't fire for native driver animations
- loading the map is super slow. I'm not sure why - we memoize the points and the cards
- need to thread through an event for the final layout of the map to get the starting diameter of the circles correct, right now they start off with the best guess we can do and don't update until the map pans
- ~` WARN  initialScrollIndex "-1" is not valid (list has 4 items) ` pops up when filtering, unclear why~ …

weather_data: implement map with cards, list with filter

---

components/observations/ObservationsFilterForm.tsx

remove the checkboxes - now the date range selector toggles open, or resets on close

Fix date picker in obs filter form

---

app.json
package.json
yarn.lock

Set minimum Android version to 8 / Android SDK 26

---

components/weather_data/WeatherStationMap.tsx

Make marker rendering even faster by only redrawing the markers whose selection state has changed

Optimize weather map marker rendering

---

components/map/AnimatedCards.tsx

Changed to animate a single parent view for both the list and the button

Fix floating list button in weather station map

---

components/forecast/WeatherTab.tsx
components/text/index.tsx

Weather forecast style updates

---

components/content/AvalancheCenterList.tsx
components/observations/ObservationsPortal.tsx
components/observations/SimpleForm.tsx
components/screens/MenuScreen.tsx
data/settingsMenuItems.ts
types/nationalAvalancheCenter/schemas.ts

add userFacingCenterId function, find the spots where it's needed

---

components/observations/SimpleForm.tsx

Undo my testing code that disabled the submit images button

---

components/KillSwitchMonitor.tsx

Reload feature flags when network comes back online

---

components/content/ActionList.tsx
components/content/Card.tsx
components/forecast/AvalancheTab.tsx
components/forecast/SynopsisTab.tsx
components/forecast/WeatherTab.tsx
components/observations/ObservationDetailView.tsx
components/observations/ObservationsListView.tsx
components/screens/MenuScreen.tsx
components/screens/WeatherScreen.tsx
components/screens/menu/AboutScreen.tsx
components/weather_data/NWACWeatherStationList.tsx
components/weather_data/WeatherStationFilterForm.tsx
components/weather_data/WeatherStationList.tsx
theme/colors.ts

screenshot | what changed
--- | ---

Update backgrounds and ActionList styles

---

components/content/Card.tsx
components/observations/ObservationsFilterForm.tsx
components/observations/ObservationsListView.tsx

Observation filtering: bugfix, styling updates

---

components/observations/ObservationsFilterForm.tsx
components/observations/ObservationsListView.tsx

Update filter badge count, only show caret on date filter

---

components/observations/ObservationsFilterForm.tsx
components/observations/ObservationsListView.tsx

Simplified the filter config to have fewer optional things, used arrays of conditions as needed.
Also added some text to the list view spinner so that it's clearer what's going on.
Fixes #511

Fix for filter conditions ANDing instead of ORing

---

components/observations/SimpleForm.tsx

Fix scrolling to form fields on submit error

---

components/observations/SimpleForm.tsx

- reduce required quality to default
- explicitly ask for compatible results on iOS

Adjust some ImagePicker options to be more compatible (hopefully)

---

App.tsx
components/content/NavigationHeader.tsx
components/observations/ObservationsListView.tsx
components/screens/ObservationsScreen.tsx

Fixes 3/4 of #520, I'll update that bug to reflect the remaining work

Fix header rendering, submit obs button rendering

---

components/form/SelectField.tsx

Set minHeight on list container, obviate need for scrollbar

---

App.tsx

Change Menu -> More in the tab bar

---

app.json

Bump the version to 1.0.1

---

.eslintrc.json
.gitignore
.prettierignore
App.tsx
components/AvalancheForecastZoneMap.tsx
components/AvalancheProblemCard.tsx
components/KillSwitchMonitor.tsx
components/TabControl.tsx
components/content/Button.tsx
components/content/InfoTooltip.tsx
components/observations/ObservationsListView.tsx
components/screens/menu/AboutScreen.tsx
components/text/HTML.tsx
components/text/index.tsx
hooks/useAllAvalancheCenterMetadata.ts
hooks/useAvalancheCenterMetadata.ts
hooks/useAvalancheForecast.ts
hooks/useMapLayerAvalancheForecasts.ts
hooks/useToggle.ts
tsconfig.json

This work is still in progress but this PR will be massive if I don't break it up. Hammering down various sources of inefficiency. Most of our issues seem to be caused by excessive re-rendering, and most of our re-rendering seems to be down to using [fat arrow functions in props](https://stackoverflow.com/questions/36677733/why-shouldnt-jsx-props-use-arrow-functions-or-bind). Ultimately I will turn on an ESLint to check for that error, but I have to fix about 200 call sites first 😵

Performance improvements

---

components/content/ActionList.tsx
components/content/AvalancheCenterList.tsx
components/content/ButtonBar.tsx
components/content/carousel/ImageList.tsx
components/content/carousel/NetworkImage.tsx
components/forecast/WeatherTab.tsx
components/observations/ObservationsListView.tsx
components/observations/SimpleForm.tsx
components/text/HTML.tsx
components/weather_data/NWACWeatherStationList.tsx
components/weather_data/WeatherStationDetail.tsx
components/weather_data/WeatherStationFilterForm.tsx
components/weather_data/WeatherStationPage.tsx
components/weather_data/WeatherStationsDetail.tsx
hooks/useToggle.ts

Mostly does what it says on the tin. Also:
- added warning to ActionList to watch for this case
- tweaked the `useToggle` interface to make it easier to use

Fixing up more fat arrow functions in render

---

components/screens/menu/AboutScreen.tsx

Update about text

---

hooks/useEASUpdateStatus.ts

Change update id display when embedded launch

---

components/observations/SimpleForm.tsx

Reduce ImagePicker selection limit based on number already picked

---

components/screens/menu/Keys.tsx
components/screens/menu/SecretMenu.tsx

We need an easy way to make sure our keys are set correctly in all scenarios (build vs update, etc)

Add key debugger to secret menu

---

.env.sample
.github/actions/expo/update/action.yaml
.github/workflows/expo_preview.yaml
.github/workflows/publish-update.yaml
App.tsx
components/screens/menu/Keys.tsx
mixpanel.ts
package.json
yarn.lock

Includes a fake mixpanel object that only logs if mixpanel is disabled. Resolves #282

Set up Mixpanel integration, plumb through keys to all build steps

---

components/AvalancheCenterLogo.tsx
hooks/useAllAvalancheCenterMetadata.ts
hooks/useAvalancheCenterMetadata.ts
hooks/useAvalancheForecast.ts
hooks/useMapLayerAvalancheForecasts.ts
types/nationalAvalancheCenter/schemas.ts

This reverts commit 6a65eab5bb491ef580dfc6f0ec424ed5fad9be12, reversing changes made to 29ff8c70473b6c2265a267077896a351a5cc3a4d.

Revert "Merge pull request #583 from stevekuznetsov/skuznets/deny-list"

---

components/observations/ObservationDetailView.tsx

Fixes https://github.com/NWACus/avy/issues/589

observations: reorder obs date and submit date

---

components/form/TextField.tsx
components/observations/ObservationFormData.ts
components/observations/SimpleForm.tsx
components/observations/uploader/ObservationsUploader.test.ts

observations: make it clear that email is not shown to the public
---
Observations: require a phone number on input
---

observations: require phone number

---

components/forecast/WeatherTab.tsx

As discussed in [Slack](https://nwactechcommittee.slack.com/archives/C03PQRCK5TR/p1701396291224719)!

Remove 'No weather stations in this zone' message

---

components/forecast/WeatherTab.tsx
components/observations/ObservationDetailView.tsx

*: don't show cards when we have no data in them

---

components/forecast/WeatherTab.tsx
types/nationalAvalancheCenter/schemas.ts

WeatherTab: be way more defensive with NWAC weather data
---
map_layer: update schema for the warning field
---

fix weather tab, map layer schema

---

components/AvalancheForecastZoneMap.tsx
components/content/ZoneMap.tsx

x-ref for issue on exact coordinates: https://github.com/react-native-maps/react-native-maps/issues/2496

map: interpret POI taps on Android

---

components/observations/ObservationFormData.ts
components/observations/SimpleForm.tsx
components/observations/uploader/ObservationsUploader.test.ts
types/nationalAvalancheCenter/schemas.ts

network: only prefetch NWAC forecasts when center is NWAC
---
observations: submit drafts when ACs request to review obs
---

Miscellaneous Fixes for CBAC

---

describe-latest-update.sh

*: add a script to write a change-log for the latest OTA

---

data/campaigns/campaigns.ts

Start showing the modal on Xmas Eve

---

components/SeverityNumberLine.tsx
components/screens/menu/SecretMenu.tsx

| Before | After |
| - | - |
| ![File (40)](https://github.com/NWACus/avy/assets/7328370/cc6c3722-6b7f-4800-92a0-7c9e408d1338) |  ![File (39)](https://github.com/NWACus/avy/assets/7328370/5fc8b75c-2cdc-4997-a7ee-5b2e61a8d208) |
Fixes #639

fix number line

---

App.tsx
components/KillSwitchMonitor.tsx
components/screens/menu/AboutScreen.tsx
hooks/useEASUpdateStatus.ts
mixpanel.ts

Fixes https://github.com/NWACus/avy/issues/590

sentry: publish source-maps by commit

---

App.tsx

PostHog requires that the Provider be inside of / a child of the navigation context. However, PostHog also spits out stack-traces and yells when the client is re-initialized, so having their Provider in part of the App that gets re-rendered only leads to spam. Initialize the client manually at the top-level so we don't see any spam.

PostHog: initialize a client manually

---

.gitignore

Just some webstorm IDE files to ignore.

chore: add .idea to .gitignore

---

hooks/useCachedImageURI.ts

Using a url that does not have a file extensions (e.g. ".jpg") will cause the underlying component to append ".png" to the URL which means the image will not be shows since no image exists at that path.
Before (no image thumbnails):
After (image thumbnails 🎉 ):

[useCachedImageURI] Fix iOS Image component issue

---

package.json
yarn.lock

This dependency is not needed.

package.json: remove expo-location

---

components/form/LocationField.tsx

Confirmed this fixes iOS and Android still works as expected. https://github.com/NWACus/avy/issues/688
for reference: https://github.com/facebook/react-native/issues/10180#issuecomment-298375648

Fix obs location for iOS

---

App.tsx

Fixes https://github.com/NWACus/avy/issues/679

App.tsx: add Sentry transactions

---

App.tsx

Fixes https://github.com/NWACus/avy/issues/631

App.tsx: send analytics ID to Sentry

---

.github/actions/expo/channel/delete/action.yaml
.github/actions/expo/update/action.yaml
app.config.ts
eas.json
eas_build_and_submit.sh
package.json
yarn.lock

Basically just following the Expo documentation here.

*: create a preview app variant

---

app.config.ts
package.json
yarn.lock

package.json: add devtools
---
app.config.ts: enforce monotonic version in preview
---

package.json: add devtools

---

components/form/TextField.tsx

To support the desired UI design.

TextField add hideLabel to allow hiding the label and comment

---

components/observations/ObservationFormData.ts
components/observations/SimpleForm.tsx
components/observations/uploader/ObservationsUploader.test.ts
components/observations/uploader/ObservationsUploader.ts
components/observations/uploader/Task.ts
components/observations/uploader/uploadImage.ts

Support tracking the state of captions and threading it through the upload task.

Add ImageAndCaption interface for SimpleForm and upload tasks

---

components/forecast/AvalancheTab.tsx

forecast: don't show the media when we have none
---
forecast: rework how we show summary content
---

forecast: rework how we show summary content

---

components/form/TextField.tsx
components/observations/ObservationImageEditView.tsx
components/observations/ObservationImagePicker.tsx
components/observations/SimpleForm.tsx
hooks/combineRefs.ts
hooks/reducerHelpers.ts
hooks/useEditViewState.ts

Image caption editing for observation form uploads.
https://github.com/NWACus/avy/assets/19795/003a6353-cf1a-4ee6-81b9-51b12e625097
**Note:** Android fails to auto-open when focusing a TextField. A potential hack is to use a `setTimeout` to open it after it's animated in.
https://github.com/NWACus/avy/assets/19795/9c9810b3-0015-462c-a81d-70039cd18f15

Image caption editing

---

App.tsx

fixes https://github.com/NWACus/avy/issues/754

App.tsx: short-circuit on Zod errors, don't retry more than 3 times

---

components/forecast/WeatherTab.tsx

WeatherTab: align NAC weather better with NWAC weather
This was likely an oversight on the last time I was working on this, or
the NWAC weather changed since then. Oh well.
Signed-off-by: Steve Kuznetsov <stekuznetsov@microsoft.com>
---
WeatherTab: adapt logic for Sierra specifically
Signed-off-by: Steve Kuznetsov <stekuznetsov@microsoft.com>
---
Fixes https://github.com/NWACus/avy/issues/760

WeatherTab: adapt logic for Sierra specifically

---

data/settingsMenuItems.ts

https://github.com/NWACus/avy/issues/797

menu: add CBAC links

---

components/observations/ObservationDetailView.tsx

Fixes https://github.com/NWACus/avy/issues/823

observations: use platform-specific share icons

---

components/avalancheCenterList.ts

The BTAC zone configuration is broken right now.

avalancheCenterList: remove BTAC

---

components/avalancheCenterList.ts

This reverts commit 8a13cf8b79d33d869ef25eff23f19a0e64dcc4bb.

Revert "avalancheCenterList: remove BTAC (#831)"

---

package.json
yarn.lock

There was a compilation error on the previous version for Android.

package.json: bump react-native-camera-roll

---

data/settingsMenuItems.ts

Fixes https://github.com/NWACus/avy/issues/840

data: add Sierra links

---

components/observations/ObservationsFilterForm.tsx

Looks like changes to react-hook-form also changed the allowable shapes that our filter config would have, which we did not capture in tsc.

observations: fix filtering

---

components/forecast/WeatherTab.tsx

WeatherTab: emit Sentry events when assumptions violated
Signed-off-by: Steve Kuznetsov <stekuznetsov@microsoft.com>
---
WeatherTab: opt snake river range out of BTAC weather
Signed-off-by: Steve Kuznetsov <stekuznetsov@microsoft.com>
---

WeatherTab: misc fixes

---

components/screens/menu/AboutScreen.tsx

Fixes https://github.com/NWACus/avy/issues/865

AboutScreen: update copy

---

App.tsx

Our initAsync must have been a relic of previous versions of the SDK and is no longer necessary.
note: I really don't understand why my changes caused `prettier` to act up and start changing other parts of the file ...

App.tsx: simplify PostHog initialization
