NWACus/avy

package.json
yarn.lock

Non-interactive builds on main branch were failing with `Task :expo:compileReleaseKotlin FAILED` ([example](https://github.com/stevekuznetsov/avalanche-forecast/actions/runs/3651725362/jobs/6169292326))
According to https://github.com/facebook/react-native/issues/35210, this should be fixed by bouncing the react-native version.

Update react-native to 0.69.7

---

package.json
yarn.lock

1. update the expo version to 46.0.15
2. move `expo-updates` from dev-dependencies into dependencies, and take the version back to one recommended by `expo doctor`
result: `eas build --non-interactive --platform android` succeeds: https://expo.dev/accounts/nwac/projects/avalanche-forecast/builds/af7dd54a-a822-493b-81e0-358cd46ee0cf
merging this should 🫰make the main branch go green

update expo to newest v46

---

App.tsx
app.json
hooks/useLocation.ts
package.json
yarn.lock

This was an experiment to see what was involved in getting `expo-location` working.
Not sure all of the requesting permission bits are set up correctly for the real app, but it is working in Expo Go at least:
ios | android
--- | ---

Make useLocation hook, prompt for location permissions

---

App.tsx
hooks/useAvalancheForecast.ts
types/nationalAvalancheCenter/enums.ts

- use today's date
- clamp fractional problem sizes before parsing
- use production NAC server instead of staging
map | forecast
--- | ---

Get avy forecasts happy again

---

App.tsx
CONTRIBUTING.md
codegen.ts
components/AvalancheCenterSelector.tsx
components/AvalancheForecast.tsx
components/Observation.tsx
components/Observations.tsx
components/TelemetryStationMap.tsx
hooks/observations-fetcher.ts
hooks/useAvalancheForecastFragment.ts
hooks/useObservations.ts
package.json
routes.ts
types/nationalAvalancheCenter/enums.ts
types/nationalAvalancheCenter/observations-queries.graphql
types/nationalAvalancheCenter/observations-schema.graphql
types/nationalAvalancheCenter/schemas.ts
yarn.lock

CONTRIBUTING.md: record what's needed for a dev env
Without the Sentry data, a bunch of errors pop up on every app open.
---
App.tsx: use shared state for center, date
This way, choosing a new center in the dev picker influences where
observations, weather data, etc are loaded from.
---
types/nac: update a field to nullable
We don't use this yet, but apparently it's nullable.
---
*: add observations client, simple pages to view them
This commit adds in:
- a GraphQL schema dumped from introspecting the endpoints the NAC
provides
- auto-generated TypeScript types for the above scehma
- semi-generated axios- and react-query-based …

*: add observations client, simple pages to view them

---

App.tsx
components/Observations.tsx
package.json
yarn.lock

ptal @stevekuznetsov 
_(note: the diff in App.tsx looks huge, but it's not - view it with whitespace changes ignored)_
I did not spend a lot of time rebuilding the Ant Design Card here, I'm sure I could get even closer to perfectly matching the Ant Design card with a bit more effort. That said, there are other things that are actually better now, like having the HTML content left-aligned with everything else!
I think the NativeBase styling props and layout classes are actually pretty nice to use and result in fairly readable code. And things like colors (`light.400`) and text sizes (`sm`) are referenced to the theme so you can change it in a single spot.
https://github.com/stevekuznetsov/avalanche-forecast/blob/98bb891bfb00b6c4ff2e62a5c559b6dfcfa291bb/components/Observations.tsx#L93-L110 …

Replace Ant Design with NativeBase

---

App.tsx
clientContext.ts
components/screens/ForecastScreen.tsx
components/screens/HomeScreen.tsx
components/screens/MenuScreen.tsx

- Remove the top-level SafeAreaView so that the map goes all the way to the top of the screen (matches Figma mocks). Other screens in the app use SafeAreaViews as needed
- Making this change fixes the extra whitespace at the bottom of the tab bar as well
- As previously discussed, moved debug settings to the "Menu" tab and removed "Debug"
iOS screenshots
home | menu
--- | ---

Fix safe area views; remove debug tab

---

App.tsx
components/AvalancheForecast.tsx
components/AvalancheForecastZoneMap.tsx
components/AvalancheForecastZonePolygon.tsx
components/DangerScale.tsx
components/TabControl.tsx
components/screens/ForecastScreen.tsx
components/screens/HomeScreen.tsx
routes.ts

- set the forecast zone title immediately, if we have it
- set global value for `darkText` to match Figma mocks
- extract `DangerScale` component from MapView, since we'll need it in Forecast view
- create `TabControl` component and add 3 tabs to top of forecast page

Forecast changes

---

components/forecast/AvalancheForecast.tsx
components/forecast/AvalancheTab.tsx
components/screens/ForecastScreen.tsx

- Split apart rendering for avalanche forecast into its own component (weather and obs will live next to it)
- Add the date / author header to the avalanche forecast tab

Add header to avalanche forecast tab

---

components/Card.tsx
components/Observations.tsx
components/forecast/AvalancheTab.tsx

pretty close to the figma mocks now (or at least one version of them 😄). not going to spend more time sweating pixels at this point when the designs are still in flux. 
figma | app
--- | ---

Make reusable Card component, rework top of avy forecast to use it

---

hooks/useAvalancheForecastFragment.ts
hooks/useAvalancheForecastFragments.ts

My previous implementation here was incorrectly adding the zone ID to the key-set for the fragments, whivh are zone-agnostic.
Only two requests now @floatplane !

hooks: correctly de-duplicate requests for products

---

components/AvalancheProblemSizeLine.tsx
types/nationalAvalancheCenter/schemas.ts

This change does the following:
- stop clamping avalanche danger size to an integer/enumerated value
- fix the logic in `AvalancheProblemSizeLine` so that it renders the danger correctly
I didn't remove `numberToProblemSize` from `enums.ts`, but it's currently unused - so maybe I should? Right now its main usefulness is an example of how to write unit tests, since we don't have any other tests 😬

Fix avalanche danger size display

---

components/AvalancheForecastZoneMap.tsx
components/Observation.tsx
components/Observations.tsx
components/forecast/AvalancheTab.tsx
components/screens/MapScreen.tsx
hooks/useMapViewZones.ts
types/nationalAvalancheCenter/schemas.ts
utils/date.tsx

what's in this PR:
- card has been reskinned with font styles and spacing as defined in figma
what's not in this PR
- ~centering cards correctly - they get off center as you scroll through. I broke something here, just haven't looked hard at it yet.~ now fixed
- various selection behaviors
- starting off with the zone list being partially visible
- scrolling the correct zone into view when map region is tapped
- moving the list out of the way when no region is selected

Map screen - forecast card styling

---

.github/workflows/ci.yaml
.github/workflows/preview.yaml
.github/workflows/publish.yaml
components/AvalancheForecastZoneMap.tsx

Similarly to 'no rating', we just want the words here, not the numerical value.
Follows up on #58

AvalancheForecastZoneCard: render 'general information' better

---

components/AvalancheDangerPyramid.tsx
components/AvalancheDangerTable.tsx
components/forecast/AvalancheTab.tsx
utils/date.tsx

This gets the danger table close to what's in Figma. I expect it could shift somewhat, since the Figma design is actually just a screenshot 😬 - not sure I've picked the right text formats, but that's a quick fix.
Known issue: the Outlook tab needs to be added, that'll be in a future PR.

Update AvalancheDangerTable styling

---

App.tsx
components/AvalancheForecastZoneMap.tsx
components/forecast/AvalancheTab.tsx
components/helpers/travelAdvice.tsx
hooks/useAvalancheCenterMetadata.ts
hooks/useAvalancheForecast.ts
hooks/useAvalancheForecastFragment.ts
hooks/useMapLayer.ts
hooks/useMapViewZones.ts
hooks/usePrefetchAllActiveForecasts.ts

api: use a client-side mapping for travel advice
We only get travel advice from the map layer and full forecast API, not
the fragment API, which makes relying on that field problematic. It
looks like the extant web application is simply using a client-side
mapping, anyway, instead of the API fields, so we can do that as well.
---
hooks: cache ~static data forever
The avalanche center metadata and map layer contain relatively static
data (like the name of the avalanche center and where it is in the
country), so we can cache these values for the lifetime of our app and
re-fetch them infrequently.
---
*: pre-fetch all data for the forecasts
On app load, we will now be fetching the center …

Improve API behavior, add top-level prefetching

---

App.tsx
components/AvalancheProblemCard.tsx
components/AvalancheProblemImage.tsx
components/Observation.tsx
components/Observations.tsx
components/forecast/AvalancheTab.tsx
components/text/HTML.tsx
components/text/HTMLRenderer.tsx

** not ready to merge yet **
1. As recommended in docs, this PR changes our internals to use the [RenderHTMLSource](https://meliorence.github.io/react-native-render-html/api/renderhtmlsource) component, which decouples renderer setup from actual rendering
2. Converts any remaining instances of the raw `RenderHTML` component to use our `HTMLRenderer` wrapper
Unfortunately this PR exposes the fact that preloading is causing ~50 re-renders of the top-level App. The following gets dumped to the console over and over:
```
WARN  You seem to update props of the "TRenderEngineProvider" component in short periods of time, causing costly tree rerenders (last update was 59.86ms ago). See https://stackoverflow.com/q/68966120/2779871 
at TRenderEngineProvider …
```

Use a common renderer to improve HTML render speed

---

babel.config.js

I added a reference to `react-native-reanimated` when adding collapsible card support in https://github.com/stevekuznetsov/avalanche-forecast/pull/43. It turns out that the package has 1 additional install step as documented [here](https://docs.expo.dev/versions/latest/sdk/reanimated/), but I missed it because I was just following instructions for installing `react-native-collapsible`.
AFAICT this change is a no-op as we don't use `react-native-reanimated` directly, but without this we would not be able to use it in our own code. 
How I found this: debugging the app on android, and happened to see a warning get thrown! Not sure why the warning is generally swallowed by default - it could be because package init happens so early.

Finish configuration of react-native-reanimated

---

components/AvalancheDangerIcon.tsx
components/AvalancheDangerPyramid.tsx
components/AvalancheDangerTable.tsx
components/forecast/AvalancheTab.tsx

1. Add the Outlook section (collapsed by default, shown expanded here)
2. Use the same component to render the Outlook and the current danger
3. Fix alignment of danger icons by adding right margin as necessary to bring them visually into line with their siblings

Avalanche outlook changes

---

App.tsx
components/AvalancheCenterSelector.tsx
components/AvalancheDangerTable.tsx
components/AvalancheForecastZoneMap.tsx
components/Card.tsx
components/DangerScale.tsx
components/Observation.tsx
components/Observations.tsx
components/TabControl.tsx
components/core/Center.tsx
components/core/Divider.tsx
components/core/HStack.tsx
components/core/VStack.tsx
components/core/View.tsx
components/core/index.ts
components/forecast/AvalancheTab.tsx
components/screens/MenuScreen.tsx
package.json
yarn.lock

Builds on #72 and does the following to get Android happier:
- add implementations of useful NativeBase components:
- VStack/HStack
- Center
- Divider
- replace use of Alert
- memoize core components
- fix for forecast cards not receiving touches on Android
Android build is still not zippy yet, but it is much better.

Finish removing NativeBase from app

---

components/AvalancheProblemCard.tsx
components/text/index.tsx

1) per @charlotteguard 's request, move the icons back to the top of the avalanche problem discussion
2) noticed that "Aspect/Elevation" wraps to two lines on my Android device; made the 2 line space consistent so that card elements line up visually (see screenshot)

move avy problem icons, adjust sizing of problem cards

---

hooks/useAvalancheForecastFragment.test.tsx
hooks/useAvalancheForecastFragment.ts

this fixes #87, and adds tests to codify the (potentially surprising) behavior of `isBetween`

Fix isBetween, add tests

---

components/content/Dropdown.tsx
components/forecast/AvalancheForecast.tsx
components/screens/ForecastScreen.tsx
components/screens/HomeScreen.tsx

Implements the new forecast header as defined in [Figma](https://www.figma.com/file/Bai2w7x0vUakL5WRjPGRg7/App---V3?node-id=97%3A89887&t=1cwZ9viaFawVGBng-0)
1) Add the active zones to a dropdown
2) Add an icon for navigating back to the map
https://user-images.githubusercontent.com/101196/214113696-ce9e04d7-217c-4206-b70d-ed84e075a620.mov

Add new header to forecast screen with dropdown and home button

---

hooks/useAvalancheCenterMetadata.ts
hooks/useAvalancheForecast.ts
hooks/useAvalancheForecastFragments.ts
hooks/useMapLayer.ts
network/prefetchAllActiveForecasts.ts

Now that we support asking the staging or production API for this data, we need to include the host in our query keys so that our caches are separate.

hooks: include host in all query keys

---

App.tsx
components/forecast/AvalancheForecast.tsx
components/screens/HomeScreen.tsx
hooks/useAvalancheCenterMetadata.ts
hooks/useAvalancheForecast.ts
hooks/useAvalancheForecastFragments.ts
hooks/useLatestAvalancheForecast.ts
hooks/useMapLayer.ts
hooks/useMapViewZones.ts
network/prefetchAllActiveForecasts.ts
utils/date.test.tsx
utils/date.tsx

hooks: use a mapping custom for options
This is common in all of the react-query documentation for capturing
options passed to a query. No reason we should buck the trend.
---
*: fetch forecasts using the latest product API
Ultimately, we will need two types of views:
1. "show me the currently-valid products for a zone"
2. "show me the valid products for a zone at some point in the past"
Due to quirks of how the date filtering works on the products API from
the NAC (filtering on the publication date, not the date for which the
product is valid), we need to split these cases up. This PR does the
first pass to allow us to fetch the currently-valid forecast.
Follow-up PRs will:
1. update our routes to not contain a date, and resolve "now" …

*: fetch forecasts using the latest product API

---

components/forecast/WeatherTab.tsx
hooks/useLatestWeatherForecast.ts
hooks/useLatestWeatherForecasts.test.tsx
hooks/useLatestWeatherForecasts.ts
utils/date.tsx

- `useWeatherForecasts` -> `useLatestWeatherForecasts`
- add a `useLatestWeatherForecast` hook to get weather for a particular zone
- make parser a little more robust when handling table entries like `Saturday Afternoon*`
- make a little more room for precipitation amounts so they don't wrap as easily, but it's still quite a tight squeeze in that space:

More weather cleanups

---

components/AvalancheForecastZoneMap.tsx
components/AvalancheForecastZonePolygon.tsx

does what it says on the tin. overall this seems like the right/expected behavior from a user perspective - we can see if the animations prevent anyone from using this successfully, but that doesn't seem like a reason *not* to allow this behavior.
(I guess we could only allow it when the drawer is visible? feels kinda arbitrary though)

Tap on a selected polygon should open forecast

---

hooks/useLatestWeatherForecasts.ts

Most region forecasts for today are crashing because of this - just making a quick patch

Keep the weather scraper from crashing on asterisks in column headers

---

hooks/useAvalancheForecastFragment.ts
hooks/useAvalancheForecastFragments.ts
hooks/useLatestWeatherForecast.ts
hooks/useLatestWeatherForecasts.ts

Realized that our singular hooks (`useAvalancheForecastFragment`, `useLatestWeatherForecast`) would never raise an error if the plural hook (`useAvalancheForecastFragments`, `useLatestWeatherForecasts`) failed.
Your first question is going to be "can't you just take the `isError` etc" off the plural hook and return it from the singular hook, and you theoretically *can* but it's super-messy. The return value from useQuery has ~30 fields and a few different states that have to be managed, and the mapping of the singular result (e.g. `UseQueryType<Product, Error>`) to the plural result (e.g. `UseQueryType<Product[] | undefined, AxiosError | ZodError>`) isn't clean.
This way, we await the result of the first query, and if it fails then the error is automatically bubbled up. It's very similar …

Fix error handling in chained hooks

---

components/forecast/WeatherTab.tsx
components/helpers/geographicCoordinates.test.ts
components/helpers/geographicCoordinates.ts
hooks/useAvalancheCenterMetadata.ts
hooks/useMapLayer.ts
hooks/useWeatherStations.ts
package.json
types/nationalAvalancheCenter/schemas.ts

This PR adds the list of weather stations to the end of the weather forecast. Like the overall weather forecast, this has only been tested with NWAC data and may need more work to function for other avalanche centers.
The flow in `useWeatherStations` is as follows:
- take the input avalanche center
- get the overall bounding box for all zones in the center
- ask Snowbound for all weather stations in the center's bounding box
- take the list of weather stations and break it down by zone, by testing station location against the zone polygon boundary
- apply any additional grouping to the weather stations, if defined (only defined for NWAC)
- return the map of zone => weather station groups
loading state | error state | loaded state
--- | --- | ---

Weather station list in weather forecast tab

---

App.tsx
app.config.ts
app.json
components/forecast/WeatherTab.tsx
components/screens/WeatherScreen.tsx
components/weather_data/WeatherStationDetail.tsx
components/weather_data/WeatherStationList.tsx
hooks/useWeatherStationTimeseries.ts
routes.ts
types/snowbound.ts
utils/date.tsx

This is *not* the finished table! But it's a useful checkpoint along the way. I've added a helpful disclaimer to the top of the UI ;)
What's working:
- rendering data from Snowbound API (last 24 hours only)
What's tbd:
- bunch of TODOs in the code, but off the top of my head
- top header, navigation, other things that aren't designed yet
- 24 hour/7 day selector
- plumb through date from top level
- cumulative snowfall column - not returned by Snowbound API, looks like it can just be synthesized on the client
- other issues as they're uncovered
app | website
--- | ---

Weather data table

---

components/forecast/WeatherTab.tsx

Bug reported by @yuliadub in Slack. Repros on iPhone 11 when setting dynamic text size to 110%.
Before | After
--- | ---

Allow the subsection header text to flex

---

.github/actions/setup/action.yaml
.github/workflows/ci.yaml
.github/workflows/preview.yaml
.github/workflows/publish.yaml

This extracts the "install Node - maybe install Expo - run `yarn install`" dance into a single reusable action, and updates the existing workflows to use it. 
Doesn't fix anything broken, doesn't break anything new. Just trying to get a better understanding of how to extract common code!

Create common setup action

---

components/forecast/WeatherTab.tsx
components/text/index.tsx
components/weather_data/WeatherStationDetail.tsx

Change weather tab detail to reflect Kaitlin's latest changes. Looks like a big change, but only because a new View got added to the hierarchy - view the diff with whitespace changes ignored. 
Also, some _very_ light refactoring on the weather data table.

Weather tab style

---

components/AvalancheForecastZoneMap.tsx
components/TelemetryStationMap.tsx
components/forecast/AvalancheForecast.tsx
components/forecast/WeatherTab.tsx
components/observations/ObservationSubmit.tsx
components/observations/ObservationsPortal.tsx

observations: use the center ID in text
---
*: pass around actual date-times, not dates
Our hooks expect to get actual date-times for their fetches, since we
will return different data from them based on what time of day it is and
when the avalanche centers roll over their forecast products. We need to
pass real date-times for that precision.
---
forecast: slightly clean up error states
This is certainly not the final pass, likely we want to do the fetches
inside of the tab so that we can render the rest of the screen correctly
around these errors.
---

*: pass around actual date-times, not dates

---

components/AvalancheForecastZoneMap.tsx

Calculate the real, relative-to-window (not parent) height of the top elements using a container that we can add the search bar to in the future. Moved the `top={12}` into a separate view in the column since for whatever reason the layout calculations could not handle the former, but are fine with the latter.
cc @floatplane 
Fixes the Android layout issues.

map: improve the calculations for the top elements height

---

components/AvalancheCenterSelector.tsx
components/AvalancheForecastZoneMap.tsx
components/TelemetryStationData.tsx
components/TelemetryStationMap.tsx
components/content/QueryState.tsx
components/forecast/AvalancheForecast.tsx
components/forecast/AvalancheTab.tsx
components/forecast/WeatherTab.tsx
components/form/LocationField.tsx
components/observations/ObservationDetailView.tsx
components/observations/ObservationsListView.tsx
components/weather_data/WeatherStationDetail.tsx
hooks/useAvalancheForecast.ts
hooks/useLatestAvalancheForecast.ts

We have a couple of similar issues coming to a head here:
- you can't nest hooks inside of hooks, so you can't cleanly close over a hook that needs some ancillary data for its inner workings
- when a screen needs data from a number of sources, say, when one of the hooks being used has further data requirements, the handling logic for any of those hooks still loading or having an error gets annoying, quick
In this commit I move the handling logic to a central component, which makes it much less onerous for a hook to simply ask for the data it needs as input.

*: close over query state in hooks

---

components/observations/ObservationsListView.tsx
hooks/useNWACObservations.ts
hooks/useObservations.ts
types/nationalAvalancheCenter/observations-queries.graphql

For a quick overview of what's going on (and to help me know I did the NWAC API correctly, let's be honest) we add media to the card overviews for observations.

components/observations: show the media in the card

---

components/forecast/WeatherTab.tsx
components/screens/HomeScreen.tsx
components/screens/WeatherScreen.tsx
routes.ts

This resolves #159. When navigating to weather station detail from the forecast tab, we push the weather data screen onto the Home tab's navigation stack. This keeps it from getting tangled with the Weather Data tab's stack, which was causing all kinds of weirdness. 
It also maps to the way Slack handles navigating to DMs with a particular user - you can get there from two different places in the Slack tab bar, and they are allowed to co-exist. So it seems like the right fix.

Fix navigation weirdness around weather data tables

---

scripts/eas-clean-pr-channels.sh

I think we end up with stray PR channels when a PR is merged before the preview build finishes. This is a pretty dumb script to just go in and clean them all up. Feel free to use your shell-fu to make it massively better @stevekuznetsov

Add a script for cleaning up old PR channels in expo

---

hooks/useCachedImageURI.ts

These were getting called with `uri` being undefined somehow.

hooks: be safer in image caching hooks

---

components/content/carousel/ImageList.tsx
components/observations/ObservationFormData.ts
components/observations/SimpleForm.tsx
components/observations/submitObservation.ts
package.json
types/nationalAvalancheCenter/enums.ts
yarn.lock

- Disable the submit button after successful submission, to prevent multiple uploads
- Fix bug with cache of uploaded media
- Add TS types for `md5` package
- Fix bug in image viewer that complains when photos don't have captions
- Plumb through setting from submit form about how photos can be re-used

Fix some submission TODOs

---

components/TabControl.tsx
components/forecast/AvalancheTab.tsx
components/forecast/WeatherTab.tsx
components/observations/ObservationDetailView.tsx
components/observations/ObservationFormData.ts
components/observations/ObservationsListView.tsx
components/screens/ObservationsScreen.tsx

_the diff looks huge, but a lot of it is whitespace changes_
1. Use the same navigation pattern as we do elsewhere:
list view | single observation
--- | ---
2. Add a drop shadow to the tabs in the forecast view:

Update some styles

---

hooks/useNWACObservation.ts
hooks/useNWACObservations.ts
types/nationalAvalancheCenter/observations.ts

We fixed this at the PHP API layer, so we don't need this client-side hackery any longer.

hooks: undo some NWAC obs hacks

---

.github/workflows/publish-build.yaml
eas_build_and_submit.sh

We need to rev the build numbers a bit to get them to a) line up and b) get above the manual stuff we did before. Only *after* that we can do the submission.

workflows: stop submitting

---

components/observations/ObservationFormData.ts
components/observations/SimpleForm.tsx
components/observations/submitObservation.ts
package.json
yarn.lock

This fixes a bug observed in this observation: https://forecasts.avalanche.org/observations/#/view/3223b09d-3a04-416c-bd5f-403402913412. The thumbnails are flipped upside-down. The original image orientation is set as upside-down, because I took the photos one-handed with the phone considered "upside-down" (lenses were along the bottom edge if that helps you visualize).
Many apps (but certainly not all!) take this orientation field into account and flip the images automatically for you. The NAC thumbnail generation pipeline does not, so the thumbnails just get saved as "normal" even though they're not.
I let @thechrislundy know about this issue on the NAC side, but in the meantime this PR works around the bug by automatically creating new copies of the images locally before uploading. …

Fix for flipped thumbnails on observation

---

components/TabControl.tsx
components/forecast/AvalancheForecast.tsx
components/observations/ObservationsListView.tsx
components/screens/ForecastScreen.tsx

There were places where we were using 100% height inappropriately - simplified, it was something like this:
```html
<VStack height="100%">
<View height={120}>
...some header content
</View>
<View height="100%">
body content. by using 100%, we're hoping to fill the remaining height of the
VStack parent, but instead we're getting _exactly_ the height of the VStack
</View>
</VStack>
```
The solution was to make the VStack use `justifyContent="space-between"` and allow the last child to flex into the whole space.
https://user-images.githubusercontent.com/101196/222279518-16a3f1ae-4900-4a69-91f3-efb4d05d3717.mp4

Fix scrollview sizing for all 3 forecast tabs

---

components/observations/ObservationDetailView.tsx

There's not a fully baked design here, so I did a bit of improvising. Generally went for tabular data reading across (label -> value) as it felt easier to read in portrait mode.
Known issue: NAC observations are not including location, so I'm hiding the map in that case. I expect we'll get that working today!

Update observation detail view styling

---

eas.json

We are still in draft mode on the app in Google Play, but perhaps if we explicitly target the release to internal testers, we won't need to upload it as a draft and then manually push buttons to send it out?

eas.json: update the config

---

.github/workflows/publish-build.yaml

I will revert this later - this just makes the workflow minimal so I can trigger it a couple times to get our Android build numbers in order.

workflows: stop doing ios, requiring tests

---

.github/workflows/publish-build.yaml
components/weather_data/WeatherStationDetail.tsx

`PcpSum` is not data that comes from the API, but it can be synthesized client-side. Also fix the label for intermittent/shot snow.
This table really needs a legend somewhere, maybe a collapsible view with text that says "What do these columns mean?".

Weather table: fix column labels, add accumulated precip column

---

components/core/HStack.tsx
components/core/VStack.tsx
components/observations/ObservationDetailView.tsx

- Bringing header styles in line with Kaitlin's mocks
- Updating the instability section
- Removing empty bits from the Weather section
- Add some smarts to `VStack` and `HStack` so that they only add space between non-null children - this has been bugging me for a while, should have fixed this long ago
one | two | three
--- | --- | ---

Detail view styling updates

---

components/observations/ObservationDetailView.test.tsx
components/observations/ObservationDetailView.tsx
package.json
yarn.lock

This is a quick follow up to #229, which tried to be clever about only rendering the pieces of the weather section that actually had data. Now it's not clever, but is provably more correct, and has tests attached to prove it.

Fix weather card rendering to deal with various permutations of missing data

---

components/observations/ObservationDetailView.tsx
components/screens/ObservationsScreen.tsx

observations: use a map marker to show the location
You are not supposed to be putting other types of elements into the
children of the map, and the map marker component from the library is
what we want here, anyway. We can't use the built-in `image` prop on the
marker since we need to re-size our marker; apparently there are
performance problems when there are many markers with custom image
children on one map, but we know we will only ever have one here.
---
logging: remove some spammy logs
These are not really that useful when we get them from a user.
---

observations: use a map marker to show the location

---

App.tsx
components/content/Button.tsx
components/content/InfoTooltip.tsx
components/content/Outcome.tsx
components/observations/ObservationsPortal.tsx
components/observations/SimpleForm.tsx
components/screens/MenuScreen.tsx
routes.ts
theme/colors.ts

- pre-process our RGBA color definitions to remove the alpha channel, so that the color is consistent no matter what it renders on top of
- update button styles to match figma (font, colors, borders)
- add a button style view for easier debugging

Update button styles

---

components/content/InfoTooltip.tsx
components/weather_data/WeatherStationDetail.tsx

This keeps #243 from crashing the app. However, the function TimeSeriesTable ultimately needs to be updated, to correctly handle the case where multiple stations have data for datetime values that are not even guaranteed to overlap.

Patch for crash on missing weather station data

---

components/observations/ObservationsListView.tsx
hooks/useNWACObservations.ts

We only allow for "newest" observation fetching today, and for that we would prefer to have stale but present cached data versus precise but missing data. If we simply cache that we're getting *any* observations for a day, and refresh hourly, we should make sure that users can come back to these screens and see something useful every time, especially since we're pre-fetching. When/if we expand to allow viewing results from a specific range in the past, we can update those calls to use a different key and cache, since we need to differentiate those from "latest" calls and we can cache those precisely.

observations: cache imprecise results

---

theme/colors.ts

Did not change other users to refer to these, as ColorValue is opaque and we're actually *using* the colors in other places for e.g. changing opacity, etc.

theme: add colors from swatches

---

components/observations/ObservationsListView.tsx
hooks/fetch.ts
hooks/useAvalancheCenterMetadata.ts
hooks/useAvalancheForecast.ts
hooks/useAvalancheForecastById.ts
hooks/useAvalancheForecastFragments.ts
hooks/useAvalancheWarning.ts
hooks/useMapLayer.ts
hooks/useNACObservation.ts
hooks/useNWACObservation.ts
hooks/useNWACObservations.ts
hooks/useNWACWeatherForecast.ts
hooks/useSynopsis.ts
package.json
types/requests.ts
yarn.lock

We were doing mostly OK by letting axios just throw exceptions, but that eats the error messages and does not disambiguate between errors on a response, errors sending the request, and errors creating the reqeust object. Axios could just publish a helpful error, but whatever.

hooks: explicitly handle axios errors

---

components/content/Outcome.tsx
components/content/QueryState.tsx
components/observations/ObservationsListView.tsx
hooks/useNACObservations.ts
hooks/useNWACObservations.ts

When a user scrolls to the bottom of the observations list, they can now push a button to load more historical observations.

observations: use infinite queries

---

components/content/QueryState.tsx
hooks/fetch.ts
hooks/useNWACWeatherForecast.ts
types/requests.ts

We likely want to extend the retry handler to every hook since 404s will always be terminal, but I'll save that for a follow-up.

hooks: handle 404s explicitly

---

hooks/useAvalancheForecast.ts
hooks/useAvalancheForecastById.ts
hooks/useAvalancheForecastFragment.ts
hooks/useAvalancheForecastFragments.ts
hooks/useAvalancheWarning.ts
hooks/useMapLayer.ts
hooks/useMapLayerAvalancheForecasts.ts
hooks/useMapLayerAvalancheWarnings.ts
hooks/useNACObservation.ts
hooks/useNACObservations.ts
hooks/useNWACObservation.ts

The LSP was starting to really grind to a halt when having to string together lots of implicit return types and zod schemas, so making these explicit improves DX by a load.

hooks: add some more explicit return types

---

App.tsx
components/AvalancheForecastZoneMap.tsx
components/TabControl.tsx
components/content/QueryState.tsx
components/content/carousel/ImageList.tsx
components/forecast/AvalancheForecast.tsx
components/forecast/AvalancheTab.tsx
components/forecast/SynopsisTab.tsx
components/observations/ObservationsListView.tsx
hooks/fetch.ts
hooks/useAvalancheCenterMetadata.ts
hooks/useAvalancheForecast.ts
hooks/useAvalancheForecastById.ts
hooks/useAvalancheForecastFragment.ts
hooks/useAvalancheForecastFragments.ts
hooks/useAvalancheWarning.ts
hooks/useMapLayer.ts
hooks/useMapLayerAvalancheForecasts.ts
hooks/useNACObservation.ts
hooks/useNACObservations.ts
hooks/useNWACObservation.ts
hooks/useNWACObservations.ts
hooks/useNWACWeatherForecast.ts
hooks/useSynopsis.ts
network/prefetchAllActiveForecasts.ts
types/nationalAvalancheCenter/schemas.ts
types/requests.ts

TabControl: handle null children
We get these when using conditional TSX to set up tabs.
---
ImageList: only render images
We were incorrectly trying to render videos here.
---
*: show the conditions blog tab when configured
Centers choose to opt into this feature using a field on the back-end
that we can see in the center meta-data, so we can show the tab for
those centers as requested.
---
hooks: always throw errors
Instead of sometimes throwing an error and sometimes returning sentinel
data, we can always throw. This is still not really that ergonomic but
at least it's simpler. …

*: show the conditions blog tab when configured

---

components/AvalancheForecastZoneMap.tsx
hooks/useAvalancheCenterMetadata.ts
hooks/useWeatherStations.ts

hooks: fix a typo
---
hooks: update a logging call
---
map: force an async re-render to handle races
It seems like sometimes our onLayout routines race with the SafeAreaView
being fully set up, and there's no way to get a race-less function here
as far as I can tell, so why don't we try just re-rendering the whole
thing in 50ms, which should be long enough on the machine to get out of
the race condition but not quite long enough to annoy humans.
---

map: force an async re-render to handle races

---

components/AvalancheForecastZoneMap.tsx
components/AvalancheForecastZonePolygon.tsx
components/content/ZoneMap.tsx
components/helpers/geographicCoordinates.ts
hooks/useWeatherStations.ts
package.json
types/nationalAvalancheCenter/schemas.ts
validate-zod.ts
yarn.lock

We are going to start consuming more sources of GeoJSON data from the SnowBound APIs, so we need a composable set of schemas here.

*: add more comprehensive GeoJSON zod schemas

---

hooks/useNWACObservation.ts
types/nationalAvalancheCenter/schemas.ts
validate-zod.ts

This helps us know if we're missing fields, but we don't add them to the schemas we use in production since we only care about the presence of fields we use, not the lack of a presence of fields we don't know about.

zod: use strict schemas in validation

---

components/observations/ObservationsFilterForm.tsx
components/observations/SimpleForm.tsx

Fixes #308 
@floatplane I messed up this IIFE ... the TypeScript `strict: true` mode had me doing back-bends and cartwheels to get async funcs in places like `onPress` to not error. Might have made the same bug in other spots.

observations: fix modal

---

components/content/AvalancheCenterList.tsx
components/content/Button.tsx
components/content/Card.tsx
components/content/Outcome.tsx
components/content/QueryState.tsx
components/observations/ObservationsListView.tsx
components/observations/SimpleForm.tsx

- avalanche center picker elements weren't center-aligned (icon/text/checkbox)
- observation list feedback from [Figma](https://www.figma.com/file/Bai2w7x0vUakL5WRjPGRg7/Native-App?type=design&node-id=1312-174816&mode=design&t=kFWAMAmCxjIJCpB3-0)
- added a `busy` prop to `Button` for the common case of needing to append an `ActivityIndicator` to the text within
- replace existing usage in observation submission
- switch to this pattern when loading more observations
https://github.com/stevekuznetsov/avalanche-forecast/assets/101196/0f1eccee-8e1e-4100-81a1-371fc1611c44

A few miscellaneous things

---

.vscode/settings.json
App.tsx
clientContext.ts
components/observations/ObservationsFilterForm.tsx
components/observations/ObservationsListView.tsx
components/screens/MenuScreen.tsx
hooks/useNWACObservations.ts
routes.ts

It's really hard to work on stuff in the summertime, so I made a time machine!
screenshot | in action
--- | ---
Notes
- I wanted a simpler way to flip *all* the parts of the app to a new day (and hopefully it's useful to browse particular days when investigating bugs). The existing mechanism in the screens section didn't change the query date for Weather Data, for example
- Observations list is still querying starting at `now`, I haven't looked into that but I assume/hope it's pretty easy to fix
- I didn't make the selected date sticky across runs
- There's nothing in the UI that tells you that you're browsing a particular date (which is one reason I didn't make it sticky)
- There's nothing to stop you from picking a stupid date like 1855, so don't do that
- I'll keep building the …

Add time machine for debugging

---

App.tsx
components/content/Button.tsx
components/content/QueryState.tsx
components/observations/ObservationsListView.tsx
components/screens/MenuScreen.tsx
hooks/useNACObservations.ts
hooks/useNWACObservations.ts
hooks/useObservations.ts
network/prefetchAllActiveForecasts.ts
theme/colors.ts

Big change: infinite scroll working with the observations list. This works with both NAC and NWAC. There is an unfortunate interaction with the date filtering option that I haven't completely figured out how to handle. @stevekuznetsov I'll tag you in a comment next to the thing to figure out.
Two additional small changes: 
- add a background tint to the pressed state of normal buttons, so you can tell when you've pressed them
- make "Reset the query cache" more selective, fixing #325 
Obligatory movie:
https://github.com/stevekuznetsov/avalanche-forecast/assets/101196/9c6753f9-2e2e-4eb9-b97a-41f2a1c3cb4c

Infinite scroll in observations list

---

App.tsx
components/AvalancheForecastZoneMap.tsx
components/modals/AvalancheCenterSelectionModal.tsx

before | after
--- | ---
there were a few things going on here!
- the avalanche center selection dialog was rendering a `QueryState` even when it wasn't supposed to be visible 🙈 
- the dialog had a chance to render before the map view was ready

Fix layout problems at startup

---

.env.sample
App.tsx
app.json
components/screens/MenuScreen.tsx
logger.ts

Take advantage of new Expo behavior to (1) automatically load `.env` files and (2) automatically make environment variables starting with `EXPO_PUBLIC_` available in the app. Added these variables:
variable | what it does
--- | ---
`EXPO_PUBLIC_SENTRY_IN_DEV` | enable Sentry in development mode
`EXPO_PUBLIC_DISABLE_LOGBOX` | prevent warnings and errors from popping up onscreen
`EXPO_PUBLIC_DATE` | pick a date other than 'latest' to start the app with
There's a sample `.env.local` file that shows how this all works.

Set up some useful env variables

---

components/form/SwitchField.tsx

It seems like the SegmentedControl needs to have its `appearance` property set explicitly - it's not aware of the Expo `userInterfaceStyle` property set in app.json.
I'd show you screenshots but getting them off my android device and onto my mac will probably take me about 30 minutes. I pasted them into an email in gmail and tried to send it, and this is what arrived:
Android is...sigh

Fix android dark mode weirdness

---

.github/workflows/expo_preview.yaml
.github/workflows/preview.yaml
.github/workflows/pull_request_opened.yaml

Does what it says on the tin (should help with #361)
Unfortunately I have to merge this to test it; workflows triggered by comments are only run on the main branch

Only generate Expo previews if /preview is in comment

---

.github/workflows/expo_preview.yaml

1. don't make it depend on CI, that just causes all those jobs to run again
2. `github.event.issue.pull_request` is a boolean, not an object - have to use `github.event.issue.number` to get the PR number

Fixes to expo-preview workflow

---

utils/date.test.ts
utils/date.ts

We're getting a bunch of `RangeError`s thrown by `formatInTimeZone` that are showing up in Sentry. I suspect they're spurious but want to know more. This just puts a wrapper around the function and rethrows any exception with a more detailed message.

Add more info to date formatting errors

---

.github/actions/setup/action.yaml
.github/workflows/ci.yaml
.github/workflows/publish-build.yaml
.github/workflows/publish-update.yaml
.github/workflows/pull_request_closed.yaml

fixes https://github.com/NWACus/avy/issues/8. Just needed to update actions/checkout@v2->v3 and ctions/setup-node@v2 -> v3, based on documentation that is where node 16 is supported. Tried on the update and seemed to not break anything. 
https://github.com/NWACus/avy/actions/runs/6294661816 -> no more warnings :D

Fix "The following actions uses node12 which is deprecated and will be forced to run on node16"

---

scripts/eslint.sh

Always run the version of ESLint specified in `package.json`
Related issue: #359

Use the locally installed version of ESLint

---

.env.sample
components/forecast/AvalancheForecast.tsx

Let's keep this feature under wraps until it's designed and polished. Related issue: #362

Hide the conditions blog tab behind an env var

---

components/content/InfoTooltip.tsx

Fixes #388. Shadow style courtesy of https://ethercreative.github.io/react-native-shadow-generator/

Add drop shadow to InfoTooltip modal

---

eas.json
eas_build_and_submit.sh
package.json

EAS Build doesn't do everything in a single step - it's more of an orchestrator that invokes a series of build steps, and it's very specific about the environment that those build steps see. This means that if you try to pass an environment variable through it, like so:
`FOO=bar eas build ...`
the substeps won't see `FOO`. 
However, you can call `set-env` from one of the build hooks that's supplied and that works great. So with this PR we now have the git revision showing up in the about screen of all the apps. This screenshot is from a local build installed on the simulator:
I added some quick notes on how to build locally and install the build on a simulator in https://github.com/NWACus/avy/wiki/Local-builds.

Get the current git hash into apps from EAS build

---

App.tsx
components/screens/MenuScreen.tsx
logger.ts
loggerContext.ts
logging/fileStream.ts
package.json
yarn.lock

~~Putting up as a draft but I think I should make at least one more change: not logging to file in release builds.~~
Logging to file in this implementation is stupidly expensive, because AFAICT you can only write whole files with the [Expo FileSystem API](https://docs.expo.dev/versions/latest/sdk/filesystem). I don't really want to keep all log lines in memory but maybe that would actually be better? At least then I wouldn't need to read the whole file before writing 🤷. Anyway, I try to minimize the badness by buffering up writes and flushing at most once per second. I'm guessing that our old logging package was doing something similar but I don't know.
The other change I made was to centralize creation of the logger object and make it a singleton.
Now, the good news: you can get badass …

Making logging to file work again

---

components/content/NavigationHeader.tsx
components/screens/HomeScreen.tsx
components/screens/ObservationsScreen.tsx
components/screens/WeatherScreen.tsx
hooks/useNACObservations.ts
hooks/useNWACObservations.ts

This takes a pass at solving the problem of “A User should be able to tell at any given point which avalanche center they are viewing for” by updating the navigation headers to include the current center icon. Many screen shots follow. Fixes #401 as well.
Also fixes a problem where the obs queries were trying to log the global root object `window`, with predictably bad results :D 
---
&nbsp; | &nbsp;
--- | ---
---
not much to see here yet
&nbsp; | &nbsp;
--- | ---

App header

---

components/observations/ObservationsListView.tsx
components/observations/SimpleForm.tsx
package.json
yarn.lock

@stevekuznetsov I'm guessing this got changed in the great Typescript tightening of the summer, in an attempt to suppress warnings about ignoring promise resolutions. 
An expression like this:
```
onPress={pickImage}
```
sets `onPress` to  the value of the function `pickImage`, while an expression like this:
```
onPress={void pickImage}
```
sets `onPress` to `undefined` - not what was intended. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/void
I found this when looking at #404, then searched for `{void` to see if I could find any others - hopefully these are the only two instances.

Fix unintentional void-ing of callback methods

---

.env.sample
App.tsx
components/observations/ObservationFormData.ts
components/observations/ObservationsFilterForm.tsx
components/observations/SimpleForm.tsx
components/observations/submitObservation.ts
components/observations/uploader/ObservationsUploader.test.ts
components/observations/uploader/ObservationsUploader.ts
components/observations/uploader/Task.ts
components/observations/uploader/uploadImage.ts
components/observations/uploader/uploadObservation.ts
components/screens/MenuScreen.tsx
package.json
tests/setupAsyncStorage.ts
types/nationalAvalancheCenter/schemas.ts
yarn.lock

First, they actually work again! Had to include the new `obs_source` param.
Second: this PR massively overhauls how we track, schedule and retry the observation jobs. This comment describes what we're doing now:
https://github.com/NWACus/avy/blob/f399cfd4a4cfc53f3e4c037432575fc087185be6/components/observations/uploader/ObservationsUploader.ts#L35-L42
The `submitObservation` method is now very stripped down. It enqueues tasks into the `ObservationUploader`, which is then in turn responsible for scheduling calls to `uploadImage` and `uploadObservation` in sequence. Modules are split apart and much easier to read IMO.
Observation uploads should now be resilient in the face of network errors and even app restarts. There are also a bunch of tests in `ObservationUploader.test.ts` where I had to …

Observation upload improvements

---

App.tsx
components/observations/uploader/ObservationsUploader.ts
components/screens/MenuScreen.tsx
eas.json
logger.ts
logging/fileStream.ts
logging/filterLoggedData.ts
package.json
yarn.lock

Does what it says on the tin. Uses the newly renamed `filterLoggedData` function to truncate large strings in logged data. Adds a copy to clipboard button to work around iOS mail issues.

Logging: copy to clipboard, more work on reducing log size

---

components/observations/submitObservation.ts
components/observations/uploader/ObservationsUploader.test.ts
components/observations/uploader/Task.ts
components/observations/uploader/uploadImage.ts

Fixes #431 
Applies a very conservative limit of 2k pixels on the longest side - we should figure out what the actual limits look like. 
Honestly it's pretty wasteful that images are going through a PHP server instead of straight to S3 but 🤷 time is finite, I get it.

Fix errors caused by uploading large images

---

components/observations/SimpleForm.tsx
components/observations/submitObservation.ts
components/observations/uploader/ObservationsUploader.test.ts
components/observations/uploader/ObservationsUploader.ts
components/screens/MenuScreen.tsx
hooks/useCachedImageURI.ts

- Make Axios ERR_NETWORK errors retryable
- Make the `useMutation` call run in offline mode
- Make the `NetworkImage` component work with local files in offline mode
- Add a debug menu button to clear the observation queue

Make observation submission better when offline

---

components/content/InfoTooltip.tsx
components/core/View.test.tsx
components/text/index.tsx
theme/colors.ts

This reverts commit 91aec5797614a5492031b0ca78ce0d884336c0f1. (PR #417)
The PR broke many background colors and @charlotteguard needs a fix quickly

Revert "colors.ts: ensure correct names are provided"

---

components/observations/uploader/ObservationsUploader.test.ts
components/observations/uploader/ObservationsUploader.ts
jest.config.ts
logger.ts
package.json
tests/mockNetInfo.ts

With this change the ObservationUploader will put itself to sleep when the device is offline, and wake up when it's back online. Added a couple of tests as well.
Also updated the Jest config to make `silent` the default so that you don't see log lines (you can override by running `yarn jest --silent=false`).

Online/offline detection for ObservationUploader

---

components/content/QueryState.tsx
components/forecast/ObservationsTab.tsx
components/form/DateField.tsx
components/form/SelectField.tsx
components/observations/ObservationsFilterForm.tsx
components/observations/ObservationsListView.tsx
components/observations/SimpleForm.tsx
hooks/useNACObservations.ts
hooks/useNWACObservations.ts
hooks/useObservations.ts
package.json
utils/date.test.ts
utils/date.ts
yarn.lock

Quite a few changes to improve the list view experience
- implement the new spec for date filtering - you can view the current season, or a date range within it, but you can't view arbitrary dates
- that said, date filtering respects the time machine, so you can warp to last season for debugging purposes
- fix a bug with dropdown items not being visible in the filter form
- clean up rendering of loading states; should get rid of duplicate loading spinners
- the list view only has one observation query active - either NWAC or NAC, but we don't need to interleave both
- you can now scroll all the way to the beginning of the season
I'll add some comments inline
Fixes: #403, #335, #439

Observations list view improvements

---

components/observations/ObservationDetailView.tsx
components/text/Text.test.tsx
components/text/index.tsx
package.json
yarn.lock

Fixes #250 
This is a conservative approach to the problem - only escaping entities when explicitly asked to. It might be ok to escape everywhere, but I'd want to spend some time looking at the app deeply before pushing a change like that out.
before | after
--- | ---

Opt-in unescaping of HTML entities in Text components

---

hooks/useAvalancheCenterCapabilities.ts
hooks/useAvalancheCenterMetadata.ts
hooks/useAvalancheForecast.ts
hooks/useAvalancheForecastById.ts
hooks/useAvalancheForecastFragment.ts
hooks/useAvalancheForecastFragments.ts
hooks/useAvalancheWarning.ts
hooks/useCachedImageURI.ts
hooks/useMapLayer.ts
hooks/useNACObservation.ts
hooks/useNACObservations.ts
hooks/useNWACObservation.ts
hooks/useNWACObservations.ts
hooks/useNWACWeatherForecast.ts
hooks/useSynopsis.ts
hooks/useWeatherForecast.ts
hooks/useWeatherStationTimeseries.ts
hooks/useWeatherStationsMetadata.ts
package.json
yarn.lock

all of the `useSomeQuery` methods had a stanza like this
```
const thisLogger = logger.child({query: key});
thisLogger.debug('initiating query');
```
which **creates a new `thisLogger` every time through the hook** and has the side benefit of logging every time through the hook. so noisy!
I changed all of them to
```
const [thisLogger] = useState(logger.child({query: key}));
useEffect(() => {
thisLogger.debug('initiating query');
}, [thisLogger]);
```
and they now render once per hook instance, as expected.

Fix query hook logging

---

components/observations/ObservationFormData.ts
components/observations/ObservationsFilterForm.tsx
components/observations/ObservationsListView.tsx
components/observations/SimpleForm.tsx
components/observations/uploader/ObservationsUploader.test.ts
components/observations/uploader/ObservationsUploader.ts
components/observations/uploader/usePendingObservations.ts
hooks/useNACObservations.ts
hooks/useNWACObservations.ts
hooks/useObservations.ts
utils/date.ts

- show pending observations in the obs list. this UX is still TBD
- when submission is complete, list updates to show the new obs
- show toasts as designed on upload form
Fixes: #429 by not making the cancel button a cancel button anymore. We still need to decide what the UX for cancellation looks like - is it a cancel button on the pending obs in the obs list?
~Still TBD:~
- ~listview doesn't refresh correctly once obs is submitted, so new obs don't show up until restart (tracking in issue #462)~
this is now fixed - the issue is that the date filters were set up to end at the exact time that the list view was loaded, as opposed to midnight on the custom date range or at the end of the season in the default case.
https://github.com/NWACus/avy/assets/101196/05007ef0-c974-471e-95c5-9957e4f28 …

Observation upload UX improvements

---

.env.sample
.github/actions/expo/update/action.yaml
.github/workflows/expo_preview.yaml
.github/workflows/publish-update.yaml
App.tsx
CONTRIBUTING.md
Updates.ts
app.config.ts
app.json
components/forecast/AvalancheForecast.tsx
components/screens/MenuScreen.tsx
network/prefetchAllActiveForecasts.ts

Expo updates: modified the startup sequence to do the following:
- check if an update is available
- download and apply it if it is
- continue startup if it's not
Tested this by manually updating the preview channel multiple times.
Sentry config: was not getting set correctly when calling `eas update`. Changed to use the new recommended env variable convention (`EXPO_PUBLIC_*`).
Sentry errors: minimize warnings for things that are disabled, should resolve https://nwac.sentry.io/issues/4511582939/?project=4504317393436672&query=is:unresolved&stream_index=8

Expo updates, Sentry config, resolve some Sentry errors

---

components/weather_data/WeatherStationMap.tsx

bf2394f had the conditional wrong, thus hiding all markers. that caused #479, which this fixes

Fix missing markers in WeatherStationMap

---

utils/date.test.ts
utils/date.ts

Android builds are throwing errors of this form, indicating that the timezone abbreviation `PST` is not recognized 😫. This PR turns the common North American abbreviations into valid IANA timezone names (e.g. `America/Los_Angeles`). It seems to work in my local testing!
```
ERROR  Error: Failed to format date: invalid time zone in DateTimeFormat():  PST, Wed Oct 25 2023 12:19:53 GMT-0700, z, PST
This error is located at:
in WeatherStationCard (created by CellRenderer)
```

Date timezone bugs

---

hooks/useAllAvalancheCenterMetadata.ts
hooks/useAvalancheCenterCapabilities.ts
hooks/useAvalancheCenterMetadata.ts
hooks/useAvalancheForecastById.ts
hooks/useAvalancheForecastFragment.ts
hooks/useCachedImageURI.ts
hooks/useMapLayer.ts
hooks/useNACObservation.ts
hooks/useNACObservations.ts
hooks/useNWACObservation.ts
hooks/useNWACObservations.ts
hooks/useNWACWeatherForecast.ts
hooks/useWeatherForecast.ts
hooks/useWeatherStationTimeseries.ts
hooks/useWeatherStationsMetadata.ts

This PR does 2 things:
1) try to avoid over-fetching at startup, by applying a `stale_time` to the prefetch queries. This actually feels like a reasonable use of `stale_time` - we might never even display the data that we prefetch, and I think it's not terrible if it's 24 hours out of date (though that's just an opinion, open to hearing others).
2) try to avoid displaying stale data at runtime by removing `stale_time` from our regular app queries.
There's a table below that breaks down what changed. Fixes #474.
&nbsp; | `cache_time` | `stale_time`
--- | --- | ---
prefetching | **changed**<br>value: same duration as the regular fetch's `cache_time`<br>it will get dropped from the cache if not refreshed by then | **changed**<br>value: 24 hours<br>an app launch after 24 hours will try to …

Adjust stale_time for prefetches and regular fetches

---

components/content/Dropdown.tsx

I think/hope this will resolve #406, but it was so inconsistent to repro that I can't be certain. This should be a more robust strategy for measuring and placing the dropdown in its expanded state, so let's merge this and see if the issue keeps happening.

Change layout measurement strategy for Dropdown

---

components/KillSwitchMonitor.tsx
components/content/Outcome.tsx

Very similar to #500 - this checks the `update-required` feature flag and presents a modal if the user needs to update. The `down-for-maintenance` flag always takes precedence, however.
Small change to `Outcome` and its `inline` behavior so that it doesn't flex to fill its whole container. This allows stacking it with a custom button. I don't think this should cause any issues elsewhere (famous last words).
TODO / nice to have
- the modal should have a link that opens the app store for the user. I'll add an issue for this so someone can pick it up.
update-required | down-for-maintenance
--- | ---

Implement updateRequired checker

---

components/TabControl.tsx

Keep tab names from wrapping

---

components/observations/SimpleForm.tsx

This definitely fixes #524 - on iOS, picking photos from cloud storage in offline mode causes crash. I suspect it fixes other weirdness but can't say for sure. It probably fixes #514.
We don't really get much info back from ImagePicker when things go wrong. The entire contents of the exception object fit on a single line:
```
ERROR  [2023-11-02T15:00:05.732Z] ERROR ImagePicker error {"error":{"code":"ERR_FAILED_TO_READ_IMAGE"}}
```
and googling for `ERR_FAILED_TO_READ_IMAGE` doesn't turn up anything useful. I couldn't really think of anything more to say than "An unexpected error occurred".
There's a different string for offline/online because that's one thing that we know can help. I don't know what else can help though 😢 
https://github.com/NWACus/avy/assets/101196/2e9c0173-5a9d-4696-bf5 …

Catch errors from the ImagePicker and display an error string

---

components/screens/menu/AboutScreen.tsx

We've all figured out that the version and build number of the binary are pretty useless when it comes to figuring out what the user is running - the crucial bit is the Expo update that they've downloaded. 
The git hash and update id identify the update very clearly, but don't give good at-a-glance information about how old the build is. This PR adds the build date to the info we display:
Copying the info now includes a build date:
```
Avy version 2.29.6 (2.29.6)
Build date 2023-11-02 17:31:21Z
Git revision 128e299
Update ID n/a (development)
```

Show build date on about screen

---

App.tsx
Updates.ts

This stuff is hard to test without an actual build and update channel, so I'm going to merge and party on the `preview` channel today.
Changes:
- Render a loading screen that seamlessly replaces the splash screen, includes a spinner
- Render that screen while we check for updates
- Add the 10 second delay when checking for and downloading updates at startup
Not implemented yet:
- Watching for updates while the app is running and prompting for restart
Movie showing the splash screen with spinner:
https://github.com/NWACus/avy/assets/101196/f21581cc-741d-474d-940e-540b8be6eb5b

Implement the 10 second startup delay when loading updates

---

components/screens/MapScreen.tsx
components/screens/menu/AboutScreen.tsx
hooks/useEASUpdateChecker.ts
hooks/useEASUpdateStatus.ts

This implements flow 3 of in-app updates (pictured below)
- we check for updates when (1) we come back to the foreground and (2) we're online
- if an update is available, we download it
- if the download succeeds, we throw up an alert and then apply the update
`useEASUpdateStatus` is the hook that manages the update state machine
`MapScreen` uses that hook to decide when to pop up an alert
`AboutScreen` was updated to display the update group id (which is the same for both Android and iOS, unlike the update ID) 
Debugging this was a PITA, because dev builds don't support Expo updates. While I was iterating, I ended up drawing a color-coded border around the main screen so I could see what state I was getting stuck in. That might be an interesting feature flag option, actually. …

Implement OTA updates on map screen

---

App.tsx
components/KillSwitchMonitor.tsx
components/screens/menu/AboutScreen.tsx
hooks/useEASUpdateStatus.ts

From the error reporting and tracking perspective, the update version is the really crucial thing we care about. App binary version is interesting, but far less important.
This PR makes that update version take primacy in Sentry, and exposes it in the about screen and in PostHog as well.
Here's the date string on the about page:
Here's the date string in the version data copied:
```
Avy version 2.29.6 (2.29.6)
Build date 2023.11.03.17.07
Git revision 11f1c99
Update group ID n/a (channel: development)
Update ID n/a (platform: ios)
```
Here's the date string showing up in PostHog as `updateBuildTime`:
Here's the date string showing up in Sentry as `release`:

Set Sentry and PostHog versions based on update build time

---

package.json
yarn.lock

This warning is SUPER buried and might not even be a problem, but you can see it in our Android build logs in the cloud:

Fix Android build warning

---

components/form/TextField.tsx
components/observations/SimpleForm.tsx

View this diff with whitespace changes ignored. 
Updates placeholder text to the blessed version. Removes support for `style` on TextInputProps. Updates placeholder text color to look less like actual text:
before | after
--- | ---

Update obs placeholder text, remove unnecessary style support from TextField

---

.env.sample
App.tsx

It's impossible to profile the first map render without adding some kind of delay. Every time you restart the app, connections are broken between the app and the dev tools, and the app gets to the map before you can reconnect them.
With this PR, you can set `EXPO_PUBLIC_PAUSE_ON_STARTUP` and the app will render a fullscreen view until you're ready to proceed:

Add option to pause at startup

---

App.tsx
Preferences.tsx
mixpanel.ts

- Create an analytics ID for each install and store it in preferences
- Track screen visits

Add screen tracking and user ID to Mixpanel

---

mixpanel.ts

You have to attach `ip` but you should not expect to see it show up directly in your events.
> As you've discovered, in order to enrich your events with geolocation data, you need to track an ip event property on your event. Mixpanel will use the  ip address in order to grab geolocation data. However, Mixpanel drops the ip address at ingestion and does not store it at rest to protect a user's privacy. (IP address can be considered PII in some countries so we avoid storing that altogether)
Confirmed this event showed up with geolocation data set, but no visible IP address:

Straighten out mixpanel IP address stuff

---

components/KillSwitchMonitor.tsx

Tested in development to make sure the correct value showed up there:

Fix channel sent to posthog

---

.github/workflows/publish-build.yaml
.github/workflows/publish-update.yaml
app.json

app.json: set runtime version policy
Our app contains dependencies outside of the Expo SDK which ship native
code. Therefore, we will be diligent to bump the runtime version of the
app whenever one of those dependencies changes. We futhermore require
that updates we ship only target the version of the app that they were
built on top of, to ensure that users on older native versions do not
receive OTA updates that are incompatible with their native layer.
---
.github: turn on OTA update publishing for release branch
We turned this off when we had to update code in the release branch that
changed native code but did not yet have a mechanism to conditionally
build OTA bundles only when no native code changed.
Signed-off-by: Steve Kuznetsov …

Version Policy Updates

---

.github/workflows/publish-update.yaml

We don't need to run CI before publishing OTA updates any more than we need to run it before publishing binary builds - only passing PRs can merge into the branch in the first place, so this is not useful.

.github: bring update publishing in line with builds

---

components/observations/SimpleForm.tsx

If we only log these errors, there is no visibility into what's happening.

observations: send errors from ImagePicker to Sentry

---

components/observations/SimpleForm.tsx
types/nationalAvalancheCenter/schemas.ts

This was causing parse errors, which in turn led the obs list to not load.
This is a NAC form option that we never supported:

Support `specific` instability distribution

---

components/observations/uploader/ObservationsUploader.ts
components/observations/uploader/Task.ts

Fixes #586. Note that the schema change is backwards compatible, in case someone has a pending task persisted on disk with an `organization` field in it.

Remove `organization` from uploaded obs

---

components/AvalancheCenterSelector.tsx
components/avalancheCenterList.ts
components/modals/AvalancheCenterSelectionModal.tsx
hooks/useAllAvalancheCenterMetadata.ts

We're finding that we can't trust avalanche center metadata to not be broken, so we need to make sure that only supported centers are loaded and we don't run into issues with failures loading centers we're not going to display.

avalancheCenters: only fetch the metadata we need

---

hooks/useWeatherStationTimeseries.ts

The NWAC website has besoke views of weather data, which require that calculated differences are not requested from the Snobound endpoint. If we ever move to make the app show weather data in line with the rest of the NAC centers, we can remove this logic and always ask for diffs.

weatherStationTimeseries: don't ask for calculated diffs on nwac

---

.env.sample
components/content/DataGrid.tsx
components/core/Center.tsx
components/core/HStack.tsx
components/core/VStack.tsx
components/core/View.tsx
components/weather_data/WeatherStationDetail.tsx
components/weather_data/WeatherStationsDetail.tsx

This PR changes the weather table - not massively, but noticeably. The new behavior is **off by default** but can be enabled in two ways:
1. set `EXPO_PUBLIC_NEW_WEATHER_TABLE=true` in your `.env` file while developing
2. or flip the `new-weather-table` feature flag in posthog
The changes are:
1. row and column headers are sticky
2. ~column widths are uniform. This might not be a long-term requirement, but it's definitely gonna be more challenging to make the column header widths line up with the data widths when they're no longer lined up in a single `VStack`.~ now applying a rough heuristic size based on label length
Marking as draft for now, I want to do a little more side-by-side testing. Feel free to give feedback/ask questions though.
Still TODO:
before | after 
--- | ---

Sticky headers on the weather table

---

components/observations/uploader/uploadObservation.ts

I tested this fix by manually setting my computer clock to 7 PM MST, which is past midnight in UTC.
without the fix | with the fix
--- | ---
Fixes #584

Fix problem with obs date > submitted date

---

components/core/Divider.tsx
components/core/View.test.tsx
components/core/View.tsx

- Remove warning suppression from View.tsx
- Remove `bgColor` alias - we only need `backgroundColor` or `bg`
- React Native style prop can be an array, so I leverage that - now the original style object is passed through unchanged, and an additional style object is created with any props passed as top-level props
There's a minor downside in that all the style props have to get written twice in View.tsx (so not DRY), but I haven't had to add a new one since I created that file way back when, so I don't think that's a major issue.
#452 remains open because of unrelated other instances of `ts-ignore`

Fix Typescript issues in View property setting

---

components/forecast/AvalancheTab.tsx
components/forecast/SynopsisTab.tsx
network/prefetchAllActiveForecasts.ts

network: only prefetch NWAC forecasts when center is NWAC
---
components/forecast: show toasts correctly
For whatever reason, `useTimeout()` needs to be used when calling
`Toast.show()` in a hook. Without that, we weren't seeing any of these
show up, ever. In addition, we now use the `useFocusEffect()` hook from
`react-navigation` for a much more robust approach to showing and hiding
this toast when folks navigate around the app while the toast is open.
---

components/forecast: show toasts correctly

---

components/AvalancheForecastZoneMap.tsx
hooks/useAvalancheForecastFragment.ts
hooks/useAvalancheForecastFragments.ts

avalancheForecastFragment: search for longer
In the Olympics, for example, we often see only one forecast a week. In
order to make sure our time machine works as expected, we need to search
longer back into the past.
---
avalancheForecastFragment: match NAC semantics
When no active forecast exists for the zone at the specified time, the
NAC latest-forecast API just gives the most recent one. Match that.
---
AvalancheForecastZoneMap: shade zones based on the requested time
When we're in the time machine, we want to show the map as it would have
appeared that day, so we need to check to see if the forecast is expired
against the requested time, not the current time.
Signed-off-by: Steve …

fix some date-time handling bits as always

---

types/nationalAvalancheCenter/schemas.ts
types/nationalAvalancheCenter/tests/mediaitem.test.ts

This isn't implemented on the NAC side yet, but they're going to start allowing people to attach PDFs to observations. This PR doesn't add support for displaying PDFs - it just does the bare minimum to keep the app from crashing when it tries to parse one of these new responses. I added a test to verify that it parses correctly.
I also added a fallback path, so if a new type gets added in the future it won't break the app - it will just get parsed as type `unknown`. 
@thechrislundy can you look at `types/nationalAvalancheCenter/tests/mediaitem.test.ts` and make sure that the structure of the object matches what you will be sending?
cc @stevekuznetsov @charlotteguard we'll want to push this out OTA soon

Don't crash if an observation has a PDF attached

---

Preferences.test.tsx
Preferences.tsx
components/screens/menu/SecretMenu.tsx

We use the "Reset preferences" option in the Secret Menu when we're testing and we want to go through startup flows again. But the unique user ID assigned when the user first runs the app is not a thing we should clear every time - we should keep it if possible! That way, we can consistently map events, feature flags etc to the same ID even after preferences are cleared.

Preserve user ID when clearing preferences

---

components/observations/uploader/ObservationsUploader.test.ts
components/observations/uploader/ObservationsUploader.ts
components/observations/uploader/Task.ts
components/observations/uploader/uploadImage.ts

This plumbs through `title` so that it shows up in the NAC media dashboard. Tested end-to-end by uploading a private ob with photos attached and verified that the title shows up as `Public Observation: <<location name>>`.
cc @stevekuznetsov @charlotteguard

Add title to uploaded images

---

components/KillSwitchMonitor.tsx
components/screens/menu/AboutScreen.tsx

This fixes #607. With this, we can get a user ID from someone and add them to a PostHog cohort, which in turn can be used to control a feature flag.
Here's my user ID displayed in the about page:
---
And here's that user ID in the "Early access" cohort in PostHog:
---
And here's the feature flag rule for a user in the cohort:
---
And here's the flag being returned as true for my user:
---
And (finally!) here's me running the new weather table because the feature flag is on:

Use same analytics ID for PostHog & Mixpanel, and show it in the About page

---

components/observations/uploader/ObservationsUploader.ts
components/observations/uploader/Task.ts
components/observations/uploader/uploadImage.test.ts
components/observations/uploader/uploadImage.ts

When we resize images before uploading, we lose EXIF metadata (AFAIK this statement is true for the Avy app _and_ for the web). A general solution for preserving the metadata is going to be hard and would require a *lot* of testing, but luckily the NAC API exposes a param for passing `date_taken` when uploading the image. So we grab the capture date from the original image's EXIF data (which is returned from the Expo image picker) and then we set the `date_taken` param appropriately.
The `captureDateFromExif` function is intentionally very conservative and failure-tolerant (and has tests to back that up). The worst case is that we fall back to the current behavior, where the "Date taken" field isn't set at all.
Here's an image I uploaded that has the "Date taken" field set correctly. It's …

Set 'Date taken' field for images uploaded to NAC

---

.github/workflows/ci.yaml

This should fix CI failures, now that https://github.com/expo/expo/pull/25822 is landed

Run the newest version of Expo Doctor

---

components/observations/ObservationsListView.tsx
data/campaigns/campaignManager.test.ts
data/campaigns/campaignManager.ts
data/campaigns/campaigns.ts
data/campaigns/useCampaign.test.ts
data/campaigns/useCampaign.ts

First change is that the campaign tracking now supports showing in multiple locations in the app. This comment describes things pretty well: https://github.com/NWACus/avy/blob/1c4e317e64ae2ce9ef529e83f1eeb009c6ede4b0/data/campaigns/campaigns.ts#L3-L17
(updated this to reflect that we're using `frequency` as opposed to `viewsPerDay`)
Now the compiler knows which campaigns and locations are valid:
Added a hook to wrap up feature flag checking, mixpanel event sending, etc. Here's Mixpanel events sent for view and click:

Campaigns: support multiple locations, mixpanel tracking, better type safety

---

components/AvalancheForecastZoneMap.tsx
components/content/CampaignModal.tsx
components/observations/ObservationsListView.tsx
components/screens/menu/SecretMenu.tsx
data/campaigns/campaignManager.ts
data/campaigns/useCampaign.test.ts
data/campaigns/useCampaign.ts

This should be basically ready to go now, I think. Feature flag is still off so merging it should be safe.
- map modal displays at most every 8 hours (this can be tuned in `campaigns.ts`)
- campaign banner in obs list is smaller, can be scrolled away
- useCampaign hook returns a stable value as long as the active screen remains focused, so you can render with it
All the buttons and whatnot are wired up and sending events.
map | list
--- | ---

Implement final(?) campaign designs, get modal working over map

---

components/screens/MenuScreen.tsx
components/screens/menu/AboutScreen.tsx
components/screens/menu/SecretMenu.tsx
components/screens/menu/Version.ts
network/sendMail.ts

Also figured we can add to the log ones as well? but can remove if you do not think that is necessary. Tried to consolidate version into a separate file since we use it a few places. Still learning how this is all set up, let me know what you think!
what the email looks like (version is weird and no git revision since running locally in an emulator):

Add version to feedback emails

---

App.tsx
components/AvalancheForecastZoneMap.tsx
components/core/FocusAwareStatusBar.tsx

On Android, you can set the status bar color (and if you don't set it, it seems you might get anything). This change makes the bar color white everywhere except the map. For the map, it inverts the bar colors, so you get white text and a translucent dark background.

Fix status bar background color on Android

---

App.tsx
components/AvalancheCenterSelector.tsx
components/AvalancheForecastZoneMap.tsx
components/content/Card.tsx
components/forecast/AvalancheTab.tsx
components/forecast/WeatherTab.tsx
components/observations/ObservationDetailView.tsx
components/observations/ObservationsFilterForm.tsx
components/observations/ObservationsListView.tsx
components/observations/ObservationsPortal.tsx
components/observations/SimpleForm.tsx
components/screens/MenuScreen.tsx
components/screens/menu/AboutScreen.tsx
components/screens/menu/SecretMenu.tsx
components/weather_data/WeatherStationDetail.tsx
components/weather_data/WeatherStationFilterForm.tsx
components/weather_data/WeatherStationList.tsx
components/weather_data/WeatherStationMap.tsx
components/weather_data/WeatherStationPage.tsx
components/weather_data/WeatherStationsDetail.tsx

App.tx: set the user-agent on requests
---
PostHog: track screen views and card interactions
Yes, both PostHog and MixPanel have automatic integration with our
navigation library and touch targets, but our navigation parameters are
generally machine-comprehensible identifiers rather than human-readable
values; also, tracking every touch is not very useful as CSS-style
parent naming for components is pretty much incomprehensible for anyone
but the dev who wrote the component yesterday. We're also likely going
to switch to PostHog from MixPanel as the PostHog free tier allows for
an unlimited number of investigations, whereas MixPanel caps us at 5.
---

PostHog: track screen views and card interactions

---

types/nationalAvalancheCenter/schemas.ts

Adds the `.GlideAvalanche` entry to the `enum AvalancheProblemName` to stop client from failing api data validation with this option in it.
Fixes: https://github.com/NWACus/avy/issues/669
Some additional things worth investigating:
- Making schema validation errors set `isError: true` and `isLoading: false` on network requests.
- Loosening some runtime validations (see NWACus/avy#657

Schemas: add AvalancheProblemName.GlideAvalanche

---

tsconfig.json

Changes were made in #674
There was a problem with `ts-node` picking up the tsconfig referred to in `extends`. #676 fixed the problem the `.tsconfig` can be reverted to what it was.

Revert SDK 50 upgrade tsconfig changes

---

components/observations/ObservationsListView.tsx

The assumption here is that the state from `usePendingObservations` is stable between calls. These changes then will crate stable references for `observationsSection` and `sections` between renders.

Memoize more ObservationListView state

---

app.json

We do not use these permissions for anything (and never have!) so there's no need to list them.

app.json: stop asking for location-related permissions

---

components/AvalancheForecastZoneMap.tsx

When we ask the NAC for the absolutely latest forecast product for a zone, it is possible for one zone to have a product that is valid for many zones. If that product is older than other, more zone-specific products, this will poison our `forecastResults` and the order in which we process this data will matter. Never use stale results when we have more recent ones already from the map layer.

map: only overwrite danger when we get a newer forecast result

---

CONTRIBUTING.md
components/AvalancheForecastZoneMap.tsx
components/screens/menu/DeveloperMenu.tsx
hooks/useAvalancheWarning.ts

The warnings endpoint can return three different types of products (warnings, watches and special bulletins). We only want the map to flash when there's an active warning.
A small fix to add 1 day to the warning fetch hook for the time machine, since the NAC API assumes a date and appends a time to it.

AvalancheForecastZoneMap: update watch/bulletin behavior

---

components/form/LocationField.tsx

We're only rounding on display, so the accuracy is not really lost, but regardless, 5 decimals is a 1.1m resolution and certainly good enough.
Fixes https://github.com/NWACus/avy/issues/630

LocationField: round to 5 decimals on lat/long

---

components/weather_data/WeatherStationDetail.tsx
components/weather_data/WeatherStationsDetail.tsx

We're trying to show the data points in the table localized to the timezone of the weather station we're looking at; the custom code for NWAC's multi-station table did not do this correctly in the past.
| Before | After |
| - | - |
| ![File (43)](https://github.com/NWACus/avy/assets/7328370/c10053e2-0d5f-4d86-858e-e1790fedeb16) |  ![File (44)](https://github.com/NWACus/avy/assets/7328370/dbe74898-1ca5-465d-9aae-1b3868946698) |

weather_data: format dates correctly in table

---

components/observations/SimpleForm.tsx

The `KeyboardAvoidingView` needs to know where on the screen the top boundary starts from to correctly calculate the positioning with the keyboard present.
Before this fix, the "Submit your observation" button cannot be scrolled to.
https://github.com/NWACus/avy/assets/19795/90b2e5ee-e824-46dd-b156-7602cf7dd797
After this fix the whole screen is still scrollable.
https://github.com/NWACus/avy/assets/19795/72f45f09-604d-4d35-9700-ed34e565c5eb

set keyboardVerticalOffset for KeyboardAvoidingView

---

.vscode/settings.json

With this change VSCode is now respecting the project's prettier configuration.
Before this prettier was using a system default _or_ some global configuration I might have which has a different `import` statement code style among other things.

VSCode prettier config

---

components/observations/SimpleForm.tsx

The keys only work if they're valid `useForm` keys from `ObservationFormData`

Constrain keys of fieldRefs

---

components/form/TextField.tsx
components/observations/SimpleForm.tsx

I saw the `todo:` and knew how to solve it. It's a bit of a doozy though.
The end result is that you can have stricter typing for the form fields. It _could_ be simplified if we only want `TextField` to ever work with `ObservationFormData`.
The end result is:
- You can't use a `name` prop for a form field that is not a string:
- It infers the names you _can_ use:

Add generics to TextField to fit with react-hook-form

---

components/observations/SimpleForm.tsx

Not sure what happened between #712 an now but the safe area is no longer needed.
Before:
After

Stop using safe area for keyboard vertical offset

---

components/observations/ObservationFormData.ts
components/observations/ObservationImagePicker.tsx
components/observations/SimpleForm.tsx
components/observations/uploader/Task.ts
components/observations/uploader/uploadImage.ts

Instead of managing `image` and `setImage` differently than other form fields, this uses the `useForm` apis to manage the `ObservationFormData`'s `images` field.
Functionally nothing has changed.

SimpleForm treat images as form field

---

.github/workflows/expo_preview.yaml

issue_comment trigger doesnt really provide us with much data about the branch/commit/etc, but we need a sha to get the expo_preview task to success at the end

Return sha of pull instead of ref when doing pull request get lookup for expo update GAH

---

.github/workflows/expo_preview.yaml

head.sha provided an : Error: No commit found for SHA: "c828abe8555ebf1516696f16a1cf5af45a74860c". Going to try the other sha that is returned from pulls.get.

Switch the sha used to mark expo_preview task as success

---

.github/workflows/expo_preview.yaml

This will simply add a comment with task status vs setting latest commit status on the PR based on github action results. The reason to take out the the setting of latest commit status is due to it not working for PRs from forked repos - it only works for PRs from repos inside of avy.

Remove marking task as success, comment on PR is enough

---

components/form/LocationField.tsx

attempt to solve https://github.com/NWACus/avy/issues/656. This changes the behavior a bit, where to select a location you now push a "check" location and "x" to clear it. The part that is not perfect is clearing the coordinates fully, you can spot that if you clear and then come back to set it again - the point will briefly be visible at the previous location if there was one. 
https://nwactechcommittee.slack.com/archives/C051KR96B2L/p1711086267002079?thread_ts=1711086244.167219&cid=C051KR96B2L

Add clearing of obs location

---

types/nationalAvalancheCenter/schemas.ts

Weather tab currently is not loading in the prod app due to this error. Doesnt look like we actually use status anywhere from a quick glance but adding the value fixes the hang on the weather tab
error in sentry: 
{
"received": "static",
"code": "invalid_enum_value",
"options": [
"active",
"inactive"
],
"path": [
"features",
100,
"properties",
"station_note",
0,
"status"
],
"message": "Invalid enum value. Expected 'active' | 'inactive', received 'static'"
},
https://nwac.sentry.io/issues/5080771829/events/67263066baec40f487ed0a32527c5c67/

Error caused by an unexpected enum 'static' in NWACWeatherStationStatus

---

components/content/NavigationHeader.tsx
components/observations/ObservationDetailView.tsx
components/observations/ObservationForm.tsx
components/observations/ObservationImagePicker.tsx
components/screens/ObservationsScreen.tsx
components/weather_data/WeatherStationDetail.tsx

weather_data: remove the concept of old weather table
We've used the 'new' weather table for the entire season and are happy
with it. No need to feature-flag this any longer.
---
observations: show divider for media
---
navigation header: resize mode to fit better
---
observations: rename 'simple' form
The 'simple' form was a name in reference to something else which we
don't support or even have in the code-base any longer, so let's name it
in a descriptive way instead.
---
observations: remove duplicate button to add photos …

Miscellaneous Fixes

---

components/observations/ObservationDetailView.tsx
types/nationalAvalancheCenter/schemas.ts

The date field is yet another time-less entity, so for now assume PST and fix this in the future to use the time zone of the center we're looking at, although that might break down in western Idaho ...
Also, fix the schema for avalanche observations that changed last year so we correctly detect inexact dates.
Fixes #772

ObservationDetailView: fix date parsing, estimation logic

---

components/forecast/WeatherTab.test.ts
components/forecast/WeatherTab.tsx

We were erroneously removing the first header which caused the current conditions to not render.
Fixes #796

WeatherTab: fix Sierra forecast adaptation

---

components/form/LocationField.tsx

This fixes the issue in #747 where the pin moved every time a user panned or zoomed in on the map. This was because no matter what the user did while interacting with the map, it would file an `onPress` that would then update the pin location. 
This fix replaces `<Pressable>` and the `onPress` with a `<View>` and `PanResponder`. The `PanResponder` keeps tracks of movements the user does on the `View` which are then used to determine if the user tapped the view or did a different gesture.

Issue 747: Stop pin from moving on map pans

---

components/form/DateField.tsx
components/observations/ObservationForm.tsx
components/observations/ObservationsFilterForm.tsx
components/observations/ObservationsListView.tsx
hooks/useNACObservations.ts
hooks/useNWACObservations.ts
utils/date.test.ts
utils/date.ts

The observations feed doesn't have any good reason to enforce a bound on how far back in time you can scroll. This paradigm was ported from the website where choosing "last season" will shoot off a request that fetches all observations for the entire season. Since we're not asking for all observations at once and doing a progressive load, there's no real reason to have this behavior in the app.
Fixes #811

*: remove observations feed date limits

---

components/forecast/AvalancheForecast.tsx

The react-navigation tab library doesn't seem to correctly re-render the view holding the tab label, so rendering a wider label when focused leads to the text getting cut off. We can always render the larger label in an invibisble way to force the correct behavior.

AvalancheForecast: work around tab library bug for headers

---

components/screens/MenuScreen.tsx
components/screens/menu/DeveloperMenu.tsx

Something with the Expo SDK 52 bump was causing this particular collapsible to not collapse and un-collapse, and I don't have the time to figure it out right now. Collapsing the Developer Menu is an edge case usability thing that is OK to lose for now.

DeveloperMenu: don't use a collapsible card

---

app.json

The react-native-maps viewer is broken on Android with the new architecture, so we need to revert this for now.
xref https://github.com/react-native-maps/react-native-maps/issues/5236

app.json: disable new architecture

---

components/forecast/AvalancheTab.tsx

Fixes https://github.com/NWACus/avy/issues/841

forecast: un-collapse sections by default

---

components/form/SelectField.tsx
components/observations/ObservationForm.tsx
components/observations/ObservationFormData.ts
components/observations/uploader/ObservationsUploader.test.ts

It looks like bumping the react-hook-form library changed the semantics of data in default values for a form that was never bound to a controller. In the past, this data remained in the values of the form, but now it does not. We were failing to validate the observation state before submitting it as we were losing the `status` field. Binding invisible and unchanging values to controllers that are disabled and not shown to the user is a simple if inelegant workaround.
Fixes https://github.com/NWACus/avy/issues/844

observations: fix form values

---

components/observations/ObservationFormData.ts

These limits are not imposed by the AFP backend for observations, so it's not entirely clear why the app client was imposing them. Users complained when they tried to submit a summary that was longer than our limit.

observations: remove length limits for form fields

---

components/AvalancheProblemLikelihoodLine.tsx
types/nationalAvalancheCenter/schemas.ts

Avalanche problems may now be rated 'certain', and we would like to display that terminology on the number line.

types: add a 'certain' likelihood

---

components/AvalancheDangerTriangle.tsx
components/AvalancheForecastZoneMap.tsx

We were not showing the correct light-blue color for zones with information but no active forecast, nor were we capturing expired forecasts correctly on the map layer.
Map layer shows light blue for current information:
| Before | After |
| - | - |
| ![File (59)](https://github.com/user-attachments/assets/959e4ed9-1cea-44cf-87a4-cde0db2cdeb5) | ![File (52)](https://github.com/user-attachments/assets/5fe4ec3c-f6d9-4cd3-b28d-b496d23bb5ab) |
Map layer shows grey for expired forecasts instead of their previous danger:
| Before | After |
| - | - |
| ![File (56)](https://github.com/user-attachments/assets/0c6a31b4-60d8-452f-8464-7dbfda02a90a) | ![File (53)](https://github.com/user-attachments/assets/59bcabde-51f7-49eb-a643-de3ac6853c36) |
Card hides expired danger rating, travel advice, and …

components: handle expired forecasts more correctly

---

components/observations/uploader/uploadObservation.ts

I'm not sure why this status override was provided in the uploader. We choose what status to send for the observation based on the forecast center's policy for observation review.

observations/uploader: remove status override

---

components/content/ZoneMap.tsx
components/form/LocationField.tsx
components/map/AvalancheForecastZonePolygon.tsx

Originally it must not have been clear that we could just shove the Feature for a zone into the GeoJSON marker and support all the varied types of geometries.
Fixes https://github.com/NWACus/avy/issues/141

components/map: use GeoJSON map marker

---

components/content/ZoneMap.tsx
components/map/AvalancheForecastZonePolygon.tsx

For whatver reason the `onPress` events on iOS are all sorts of messed up when we use `Geojson` markers, the events do not get a `coordinates` object passed in, which we need.

components/map: use many Polygons over Geojson

---

components/AvalancheForecastZoneMap.tsx
components/forecast/AvalancheTab.tsx
components/forecast/WeatherTab.tsx
components/observations/ObservationDetailView.tsx
components/observations/ObservationForm.tsx
components/observations/ObservationsListView.tsx
components/weather_data/WeatherStationDetail.tsx
components/weather_data/WeatherStationList.tsx
components/weather_data/WeatherStationMap.tsx
components/weather_data/WeatherStationPage.tsx
components/weather_data/WeatherStationsDetail.tsx

We have lots of events with `""` as the center ID, which leads me to believe that there are component renders where we somehow don't have props or something? Wild.

*: only send PostHog data when we have it

---

App.tsx

The PostHog documentation states that auto-capture should be off-by-default and entirely opt-in, but the behavior we're seeing is that it seems to be on for us even though we do not turn it on. We do *not* want their automated screen captures, so this commit tries to make that explicit.

App.tsx: tune PostHog auto-capture

---

App.tsx

These are cool in theory but will generate a large volume of useless events unless we have something specific we are trying to do with them.

App.tsx: stop tracking touches in PostHog

---

components/observations/ObservationDetailView.tsx

Enable scroll and zoom on observation maps
Closes #893
1. Open any observation. You should be able to move around in the map as well as pinch to zoom in/out

Observation Map Controls

---

components/map/AnimatedCards.tsx

Fixes the scrolling behavior of the `AnimatedCards` component on Android. The `scrollEventThrottle` parameter that had previously been added was causing an issue with the cards scrolling on Android devices. This fixes the issue by removing the continuous calls to `handleScroll`, in favor of calling it a single time when the `onMomentumScrollEnd` event fires.
Note I have not tested this on Apple devices.
Fixes #871, and #692.

Fixes scrolling on cards

---

FeatureFlags.tsx

We don't want to race between registration and feature flag resolution, as information from registration is necessary for resolving the flags.

FeatureFlags: wait for registration before fetching flags

---

App.tsx

It may not always be quick or even possible to load feature flags at startup time. To ensure the most important flags are present, we can pre-compute them and use the values to bootstrap the client.

App: bootstrap feature flags.

---

App.tsx

We regressed this functionality in d0bf3a11981e4120a9f9753dfc2af611c6a9745f. Following the migration guide to update:
https://docs.sentry.io/platforms/react-native/migration/sentry-expo/#review-sentryinit-options

App.tsx: don't send Sentry events in dev unless configured

---

components/content/NavigationHeader.tsx
components/observations/ObservationDetailView.tsx

Removes the avy center logo from the top header for both observation and weather data screens. Replaces it with the share button on observation screens.
Fixes #822 .
Observations screen before and after:
Weather data screen before and after:

Replaces avy center logo in top header with share button

---

components/forecast/WeatherTab.tsx

We were erroneously not capturing analytics when users loaded the NWAC weather forecast tab.

NWACWeatherTab: record analytics

---

components/weather_data/WeatherStationsDetail.tsx

Increases the width of weather data table columns for headers with more than 5 characters. Previously these headers were breaking into multiple lines on some devices. Fixes #923.

Fixes weather data table headers

---

components/weather_data/WeatherStationsDetail.tsx

We were previously not handling unknown field names, so we'd crash when we got new field types from the SnowObs API. This commit handles the unknown field case and adds some short names for battery voltage.

WeatherStationsDetail: handle unknown fields

---

components/content/carousel/carouselV2/MediaCarousel.tsx
components/content/carousel/carouselV2/MediaViewerModal/ImageView.tsx
components/content/carousel/carouselV2/MediaViewerModal/MediaContentView.tsx
components/content/carousel/carouselV2/MediaViewerModal/MediaViewerModal.tsx
components/observations/ObservationDetailView.tsx

This adds gesture support to `ImageView.tsx` to bring the custom MediaViewer functionality back to what it was with the old  image viewer. Three gestures are added to the view: pinch, pan, and double tap.
These gestures use the `react-native-gesture-handler` package while the animations use `react-native-reanimated`. These packages are built to work together, and they were packages that are already being included in the repo.
The design decisions I made with passing in an optional native gesture and an option fullScreenWidth into the `ImageView` was to hopefully make it as reusable as possible.
I decided to go with this package over the built in `GestureResponder` that's provided by React Native because `react-native-gesture-handler` has better performance and platform support. It's built …

Add gesture Support to ImageView.tsx
